---
number-depth: 2
---

# Fetal and Neonatal Death Workflows and Documentation

## Executive summary

<br/>

### The issues we are trying to solve:

1. Each year there are a few dozen babies delivered at < 23 wk GA where the baby has died before delivery or dies shortly after birth.
2. These are emotionally charged moments for families and we may upset them unintentionally through some of our practices. There are some "best practices" to share that help avoid those upsets.
3. There is confusion around the many regulatory specifics for these babies. We wanted to provide some decision support for finding one’s way through those specifics.
4. There are differences in expectation around the division of work and workflow between pediatricians and obstetricians and between nurses and physicians. We can clarify some of the general guidelines while recognizing the need to individualize roles in specific situations in the spirit collegiality and empathy to the family and team members.

<br/>

### Key things we hope to change / improve in our practices:

1. Babies with signs of life are live born, regardless of gestational age
2. "Uterogestational" age = gestational age in the usual sense (based on best obstetrical estimate EDC)
3. Live born babies of any GA are pediatric patients though the expected bedside involvement of the pediatrician is very limited through well-
established local OB/Neonatal workflows
    a. Paperwork responsibilities: H&P, orders, discharge note, declaring death, death certificate
    b. The NICU team usually will attend the delivery only if GA ≥ 22 wk
    c. The obstetrician will manage the parents’ questions and concerns around the baby but the pediatrician will be available for specific concerns if requested by the obstetrician or parent
4. The remains of pre-viable babies need to be treated with respect and sensitivity: including bundling, sending remains to morgue, avoiding handling as surgical path specimens except when specific studies are ordered
5. Workflows: Local med center should develop and maintain OB/Neonatal workflows to maximize the quality and efficiency of care for all concerned (babies, mothers, pediatrician/neonatologists, OB/GYN, nursing, pathology, medical records, decedent affairs)

<br/>

### Navigation of this document:

The document is divided into 4 sections: 

1. [Algorithm for classifying & Documenting deliveries in California](#sec-death-workflows-sec1)
2. ["The fine print" on classifying deliveries in California (Live birth & fetal death definitions – State code)](#sec-death-workflows-sec2)
3. [Workflow and documentation FAQs](#sec-death-workflows-sec3)
    a. Workflow: Who does what at the bedside at delivery
    b. Documentation: MD KPHC charting points on baby
    c. Workflow: Disposition of remains issues after death
    d. Documentation: Disposition of remains issues after death
4. [Illustrative scenarios](#sec-death-workflows-sec4)
5. [Approval groups & committees](#sec-death-workflows-sec5)

### Section 1: Algorithm for Classifying & Documenting Deliveries in California {#sec-death-workflows-sec1}

:::{.column-page-inset-right}

```{mermaid}
flowchart TD
  A["Signs of life at or after expulsion?<br><em>see live birth defined on next page<br>(HR OR limb movement or trunk movement or<br>respiratory muscle movement or pulsating cord,<br>regardless of gestational age)</em>"] --> B["Yes"]
  A --> C["No"]
  B --> D["Live birth"]
  D --> E["Died in first 30 days?"]
  E --> F["Yes"]
  F --> G["<span style='color:red;'>Neonatal Death</span>"]
  E --> H["No"]
  H --> I["Still Alive"]
  C --> J["Did the mother intend this<br>delivery to be classified as a<br>TAB/EAB?"]
  J --> K["No"]
  K --> L["GA at delivery? <em>(GA is the 'usual'<br>obstetrical estimate)</em>"]
  L --> M["<span style='color:red;'>Fetal demise GA < 20weeks</span>"]
  L --> N["<span style='color:red;'>Fetal demise GA ≥ 20weeks</span>"]
  J --> O["Yes"]
  O --> P["<span style='color:red;'>TAB</span>"]
```

:::

### Section 2: "The Fine Print" on Classifying Deliveries in California (Live Birth & Fetal Death Definitions – State Code) {#sec-death-workflows-sec2}

* **Live birth defined**: "Live Birth" means the complete expulsion or extraction from its mother of a product of conception (irrespective of the duration of pregnancy) which, after such separation, breathes or shows any other evidence of life such as beating of the heart, pulsation of the umbilical cord, or definite movement of voluntary muscles, whether or not the umbilical cord has been cut or the placenta is attached. (California Code of Regulations, Title 17, Section 915).
* **Fetal death defined**: "Fetal death" means a death prior to complete expulsion or extraction from its mother of a product of conception (irrespective of the duration of pregnancy); the death is indicated by the fact that after such separation, the fetus does not breathe or show any other evidence of life such as beating of the heart, pulsation of the umbilical cord, or definite movement of voluntary muscles (referenced on 9/21/2018 from CDC summary of state regulations at <https://www.cdc.gov/nchs/data/misc/itop97.pdf>)

### Section 3: Workflow & Documentation FAQs {#sec-death-workflows-sec3}

#### Workflow: Who Does What at the Bedside at Delivery?

| **Activity or Documentation Required**                                | **TAB**                                                                                                                                                                          | **Fetal Demise GA < 20 wk**                                                                                                                                                      | **Fetal Demise GA ≥ 20 wk**                                                                                                                                                     | **Live birth who dies (i.e. Neonatal Death)**                                                                                                  |
|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|
|     Delivery summary (Stork)                                          |     Only if in L&D                                                                                                                                                               |     Only if in L&D                                                                                                                                                               |     Yes                                                                                                                                                                          |     Yes                                                                                                                                        |
|     Is Baby assigned MRN?                                             |     Only transiently: MRN assignment is required to make the Delivery Summary available for documentation. Selecting Fetal Demise in Delivery Summary will inactivate the MRN    |     Only transiently: MRN assignment is required to make the Delivery Summary available for documentation. Selecting Fetal Demise in Delivery Summary will inactivate the MRN    |     Only transiently: MRN assignment is required to make the Delivery Summary available for documentation. Selecting Fetal Demise in Delivery Summary will inactivate the MRN    |     Yes                                                                                                                                        |
|     Is KPHC chart created for baby?                                   |     No                                                                                                                                                                           |     No                                                                                                                                                                           |     No                                                                                                                                                                           |     Yes                                                                                                                                        |
|     Which physician is the attending physician in the baby’s care?    |     OB/GYN                                                                                                                                                                       |     OB/GYN                                                                                                                                                                       |     OB/GYN                                                                                                                                                                       |     Pediatrician/neonatologist                                                                                                                 |
|     Who is attendance at delivery to care for baby?                   |     OB team                                                                                                                                                                      |     OB team                                                                                                                                                                      |     OB team                                                                                                                                                                      |     NICU team generally only attends if GA > 22 wk but will attend on a case by cases basis at request of     parent or a member of OB team    |
|     Where should baby be cared for till     death?                    |     Mother’s room                                                                                                                                                                |     Mother’s room                                                                                                                                                                |     Mother’s room                                                                                                                                                                |     Per mother’s preference     (Mother’s room or NICU)                                                                                        |
|     Who declares death?                                               |     n/a                                                                                                                                                                          |     n/a                                                                                                                                                                          |     n/a                                                                                                                                                                          |     Pediatrician/neonatologist. Typically the RN will call the MD when baby's heartbeat has ceased to beat.                                    |

#### Documentation: MD KPHC Charting Points on Baby

| **Activity or Documentation Required**                                         | **TAB**                    | **Fetal Demise GA < 20 wk** | **Fetal Demise GA ≥ 20 wk** | **Live birth who dies (i.e. Neonatal Death)**         |
|--------------------------------------------------------------------------------|----------------------------|-----------------------------|------------------------------|-------------------------------------------------------|
|     Is baby admission and discharge note needed for baby?                      |     No                     |     No                      |     No                       |     Yes (admit and discharge note may be combined)    |
|     Are admission/discharge orders required for baby                           |     No                     |     No                      |     No                       |     Yes                                               |
|     If pathological exam desired, what     type of exam for baby’s remains?    |     Surgical path order    |     Surgical path order     |     Autopsy                  |     Autopsy                                           |
|     If pathological exam desired, is autopsy form needed?                      |     No                     |     No                      |     Yes                      |     Yes                                               |

#### Workflow: Disposition of Remains Issues after Death

| Activity or Documentation Required                                                                        | TAB                                                                                          | Fetal Demise GA < 20 wk                                                                  | Fetal Demise GA ≥ 20 wk                 | Live birth who dies (i.e. Neonatal Death) |
|-----------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------|------------------------------------------|-------------------------------------------|
|     How should the remains of a fetal demise or neonatal death be attired on labor and delivery floor?    |     Bundled (not in a surgical basin)                                                        |     Bundled (not in a surgical basin)                                                    |     Bundled (not in a surgical basin)    |     Bundled (not in a surgical basin)     |
|     Where should baby’s remains be stored in the pathology dept?                                          |     Usually to surgical specimen receiving <br><br>    Morgue if parents considering     mortuary    |     Usually to surgical specimen receiving <br><br>    Morgue if parents considering mortuary    |     Morgue only                          |     Morgue only                           |
|     May family make private arrangements for remains?                                                     |     Yes                                                                                      |     Yes                                                                                  |     Yes                                  |     Yes                                   |
|     May family leave remains to hospital for disposition?                                                 |     Yes                                                                                      |     Yes                                                                                  |     Yes                                  |     Yes                                   |

#### Documentation: Disposition of Remains Issues after Death

| **Activity or Documentation Required**                                                | **TAB**                                    | **Fetal Demise GA < 20 wk**                | **Fetal Demise GA ≥ 20 wk**              | **Live birth who dies (i.e. Neonatal Death)** |
|---------------------------------------------------------------------------------------|--------------------------------------------|--------------------------------------------|-------------------------------------------|-----------------------------------------------|
|     Is birth certificate required?                                                    |     No                                     |     No                                     |     No                                    |     Yes                                       |
|     Is "Regular" "Certificate of Death" required?                                     |     No                                     |     No                                     |     No                                    |     Yes                                       |
|     Is "Fetal certificate of death" required?                                         |     No                                     |     No                                     |     Yes                                   |     No                                        |
|     If parents want to send remains to a mortuary, what paperwork is needed?          |     "Release to mortuary- coroner" form    |     "Release to mortuary- coroner" form    |     Release to mortuary- coroner" form    |     Release to mortuary-coroner" form         |
|     If parents want to have remains handled by hospital, what paperwork is needed?    |     "retain and dispose" form              |     "retain and dispose" form              |     Special county release form           |     Special county release form               |

### Section 4: Illustrative Scenarios {#sec-death-workflows-sec4}

:::{.column-page-inset-right}

| **Scenario / Question**                                                                                                                                                                                                | **Answer**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|     There was a crash C-section for bradycardia. The baby did not have a HR or movement at birth and did not respond to resuscitation. Is the baby a fetal death or     live birth who failed resuscitation?             |     Fetal death                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|     The pediatricians at our center haven’t been involved in periviable live births below a certain gestational age. How many babies might we be called to see if we now became involved?                                |     The burden for neonatal physicians is very small and there will be little change in practice. Between 2010 and 2018 only about 35 babies were born annually in the whole Region. In 2018 all of the babies born alive at 22 wk GA were seen by pediatricians. The large majority of the 15 babies born alive at 20≤GA<22 wk were seen by pediatricians. Of the 11 babies born alive at     GA < 20 wk no pediatricians were involved.                                                                                                                                                                                                                                                                                                                                                                                                                              |
|     We haven’t consistently called the pediatrician low GA live births. If pediatricians are now called, will that inadvertently encourage resuscitations for babies that would otherwise be allowed to pass quietly?    |     The issue of whether or not to resuscitate a baby should be driven by careful discussions between the physicians and parents and not by the presence or absence of a neonatal team at delivery<br><br>     The choice of whether a neonatal team should attend a delivery should be part of those careful discussions<br><br>     A neonatal team’s presence at a delivery does not mandate resuscitation. The presence of the team, if called, is meant to ensure the most appropriate care is provided to the baby and assure the parents and non-neonatal staff that the appropriate level of support is being provided<br><br>     As with any delivery the pediatrician should respond to a request to come to the delivery room if requested by a member of the OB team as a matter of professional duty, whether or not a resuscitation will be performed    |
|     The baby made some arching truncal movements but there was no heart rate or signs of responsiveness. Is     the baby a live born?                                                                                    |     Yes. It is problematic in a number of ways to treat a baby some might consider alive as already     dead. Any sign of life is treated by California state as evidence the baby is liveborn. It’s better to error on the side of calling a baby a live born when there is difference of opinion.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|     Does GA or BW change management of a baby with a     heartbeat at birth?                                                                                                                                             |     No. There is no minimum GA or BW below which a baby with signs of life at birth is not treated     as a live birth                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|     Does GA or BW change management of TAB?                                                                                                                                                                              |     No. There is no maximum GA or BW for TAB                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|     Does presence of FHR before delivery change above management?                                                                                                                                                        |     No. It is the baby’s status at delivery that determines management                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|     Is an induction at GA 24 wk for "inevitable abortion" that results in a fetal demise classified as a TAB?                                                                                                            |     No (unless that’s what the mother wants it to be categorized)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|     Is an 18 wk delivery with a HR for a few seconds classified as a miscarriage or a live birth?                                                                                                                        |     Live birth. There is no minimum GA or BW below which a baby with signs of life at birth is not treated as a live birth.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|     What about a 10 wk delivery that barely looks like a baby but has a visible heartbeat?                                                                                                                               |     Live birth unless the remains are not "recognizable anatomical parts" 7054.4.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|     I don’t think it’s humane to ask a family to fill out a birth certificate for an 18 wk death just because there was a visible heartbeat. What can I do?                                                              |     The problem is that it is not technically legal to categorize the death after birth as a fetal demise. Convincing the family or nurses that a tiny baby with signs of life is not really alive is fraught for many reasons. So you need to devote your efforts to make this moment humane     within the context of the law under these sad circumstances. The parents are not required to give the baby a first name                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|     Spontaneous abortion, inevitable abortion, intrauterine fetal demise, stillbirth, miscarriage, fetal death and fetal demise, induced abortion: how do I     decide which terms should be used?                       |     "Fetal demise" is the only term used in "Stork". "TAB" and "abortion "are the only terms used in the OB history. The other terms do not have strong consensus on definitions and can cause confusion                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|     A mother presents with a spontaneous abortion in the ED or office: do I need to fill out a KPHC "delivery summary"?                                                                                                  |     No. The delivery summary is intended to be an inpatient document                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |

:::

### Section 5: Approval Groups & Committees {#sec-death-workflows-sec5}

This document has been approved by the following groups & committees:

*	Women’s & Children’s Health Leadership Team
*	NICU Directors
*	OB/GYN Chiefs Group
*	Family Centered Care (FCC) & Labor and Delivery Nursing Leadership
*	NICU Nursing Leadership
*	Perinatology Leadership
