---
number-depth: 2
---

# Phone Numbers

## Riverside Medical Center

<br/>

:::{.column-page-right}

| **Office**                 | **Contact** | **Extension**          | **Tie Line** | **Phone Number** |
|----------------------------|-------------|------------------------|--------------|------------------|
| Employee Health            | Maria RN    |                        | 8-247-4356   |                  |
| L&D                        |             | 4770 (old), 3160 (new) |              |                  |
| FCC East                   |             | 3300                   |              |                  |
| FCC West                   |             | 3332                   |              |                  |
| Cardiology                 |             | 3353                   |              |                  |
| Pediatric Surgery - Fontana | Edward Yoo, MD |                   |              |  323-699-0523    |
| NICU Pharmacy              |             | 3617                   |              |                  |
| Outpatient Pharmacy        |Joules Bernabi| 4498                  |              |                  |
| Outpatient Pharmacy supervisors |Tony, Miriam| 3103               |              |                  |
| Pharmacy - General         |             | 3260 #4                |              |                  |
| Pharmacy                |Jacqueline Dang | 3673                   |              |                  |
| Clinical lab               | Dr. Taira (Med Director) | 4199      |              |                  |
| Pathology                  |             | 4064                   |              |                  |
| Chemistry                  |             | 4064                   |              |                  |
| Blood Bank                 |             | 4067                   |              |                  |
| Risk Management | Melanie Dastrup RN, MSN-Ed, CPHQ | 5316 | 8-258 | 951-353-5316 or 951-212-4524 (cell)          |
| ED - Riverside             |             | 3945                   |              | 951-353-3945     |
| ED - Fontana               |             |                        |              | 909-427-7373     |
| ED - Moreno Valley Case Manager               | 6572            |                        |              |    |
:::

<br/>
<br/>
{{< pagebreak >}}

## Regional NICUs {#sec-regional-nicus}

|                         | **KP Tie line** | **Land Line** |
|-------------------------|-----------------|---------------|
| **Fontana NICU**        | 8-332-7300      | 909-302-7300  |
| **Ontario NICU**        | 8-264-5590      | 909-724-5590  |
| **Riverside NICU**      | 8-258-3170      | 951-353-3170  |
| **Moreno Valley NICU**  |                 | 951-243-2050  |
| **Anaheim NICU**        | 8-215-7040      | 714-644-7040  |
| **Baldwin Park NICU**   | 8-370-7340      | 626-851-7340  |
| **Downey NICU**         | 8-327-7550      | 562-657-7550  |
| **Irvine NICU**         | 8-238-7040      | 949-932-7040  |
| **LAMC NICU**           | 8-363-9411      | 323-783-9411  |
| **Pan City NICU**       | 8-350-2822      | 818-375-2822  |
| **San Diego NICU**      | 8-396-3400      | 858-266-3400  |
| **South Bay NICU**      | 8-340-6927      | 310-257-6927  |
| **West LA NICU**        | 8-390-2481      | 323-857-2481  |
| **Woodland Hills NICU** | 8-348-3360      | 818-719-3360  |

<br/>
<br/>
{{< pagebreak >}}

## Pediatrics Department Contact {#sec-pediatrics-department-contact}

| **DEPARTMENT**                                   | **NAME**                                                                                    | **LOCAL**                                                                                                                                                                                                                 | **PAGER/CELL**                                                           | **NURSING STATION**                            | **OFFICE/VOICE   MAIL**               | **CASE MANAGER**                       |
|----------------------------------------------------|---------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------|------------------------------------------------|---------------------------------------|----------------------------------------|
| **ADD Sx 6 or under**                              | child parent interaction therapy by County Childrens Services                               |                                                                                                                                                                                                                           | 951-358-4520                                                             |                                                |                                       |                                        |
| **ADD/developmental**                              | TBD                                                                                         | RIV                                                                                                                                                                                                                       |                                                                          |                                                |                                       | for pt. 951-353-3199                   |
|                                                    | Edward Curry                                                                                | RIV/FON                                                                                                                                                                                                                   | 951-675-9016                                                             | 8-258-4326                                     | 8-258-4524                            | Elvia Guerrero x3119                   |
|                                                    | Cindy Evans                                                                                 | OC                                                                                                                                                                                                                        | 888-988-2800                                                             | 8-237-6685                                     |                                       |                                        |
|                                                    | Jay H. Lee                                                                                  | OC(tustin)                                                                                                                                                                                                                | 888-988-2800                                                             |                                                |                                       |                                        |
| ***autism case manager                             | Lisa snider                                                                                 | OC                                                                                                                                                                                                                        | 888-988-2800                                                             |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **ALLERGY/IMMUNOLOGY**                             | Lien Lai -specialized in pediatric pt                                                       | RIV-Wildomar                                                                                                                                                                                                              |                                                                          | 8-260-3323                                     |                                       |                                        |
|                                                    | Purvee Shah                                                                                 | RIV                                                                                                                                                                                                                       |                                                                          | 8-258-4453   or 4413                           | 8-258-5869                            |                                        |
|                                                    | Tranhoai Nguyen                                                                             | RIV                                                                                                                                                                                                                       |                                                                          | 8-258-4453                                     |                                       |                                        |
|                                                    | Niya Wanich                                                                                 | LA                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **CARDIOLOGY**                                     | Bobby Daftari                                                                               | RIV                                                                                                                                                                                                                       | 310-650-1963(cell)      310-626-8732(fax-ECG)                            | 8-258-5503                                     | 8-258-3353                            | Nicole Hutson x5464                    |
|                                                    | Eugene Hwang                                                                                | FON                                                                                                                                                                                                                       | 909-876-2736                                                             | 8-250-5451                                     | 8-250-7156                            |                                        |
|                                                    | Ila Sangadkor                                                                               | OC                                                                                                                                                                                                                        |                                                                          | 8-230-2720                                     |                                       |                                        |
|                                                    | John Charles Loo                                                                            | OC                                                                                                                                                                                                                        | 562-272-5809                                                             | 8-235-5710                                     |                                       |                                        |
|                                                    | Ronald Rosengart                                                                            | LA                                                                                                                                                                                                                        | 323-699-4450                                                             | 8-363-5310                                     | 8-363-8120                            |                                        |
|                                                    | Tim Degner                                                                                  | LA                                                                                                                                                                                                                        | 323-821-7428                                                             | 8-360-5323                                     |                                       |                                        |
|                                                    | Morris Salem                                                                                | LA                                                                                                                                                                                                                        | 323-821-6704                                                             | 8-363-5353                                     |                                       |                                        |
|                                                    | Ahktar                                                                                      |                                                                                                                                                                                                                           | 818-250-0025                                                             |                                                |                                       |                                        |
|                                                    | Swilley                                                                                     |                                                                                                                                                                                                                           | 310-609-4889                                                             |                                                |                                       |                                        |
|                                                    | Joseph Mares                                                                                | DOW                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    | Matthew Russell                                                                             | LA                                                                                                                                                                                                                        | 323-333-2662                                                             |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **CRANIOFACIAL/PLAS TIC**                          | Trevor Hoffman (craniosynostosis)                                                           | WLA                                                                                                                                                                                                                       | 949-233-8099                                                             | 8-250-5993                                     | 8-390-2368      8-250-4055            | Pamela   Hoffman, 323-857-2368         |
|                                                    | Zhao (plagiocephaly)                                                                        | FON                                                                                                                                                                                                                       | OR   PT-RIV                                                              |                                                |                                       |                                        |
|                                                    | Yohan Shin                                                                                  | FON                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **PEDS DERMATOLOGY**                               | Arlene Tsuchiya                                                                             | OC                                                                                                                                                                                                                        | 714-387-1687                                                             | 8-237-7975                                     | 8-234-3405                            |                                        |
|                                                    | Louise Gordon                                                                               | OC                                                                                                                                                                                                                        |                                                                          | 8-236-4371                                     |                                       |                                        |
|                                                    | Valencia Sosa                                                                               | LA                                                                                                                                                                                                                        |                                                                          |                                                | 8-363-4158                            |                                        |
|                                                    | Linda Wong                                                                                  | BP                                                                                                                                                                                                                        | 626-728-5481                                                             | 8-370-5001                                     | 8-370-5004                            |                                        |
|                                                    | Pamela Nemzer                                                                               | BF                                                                                                                                                                                                                        |                                                                          | 8-327-2640                                     | 8-327-2565                            |                                        |
|                                                    | Susan Boiko                                                                                 | SD(San   Marcos)                                                                                                                                                                                                          | 619-682-0709                                                             | 8-276-4244                                     | 8-276-4058                            |                                        |
| -vascular birth mark clinic                        | under Derm                                                                                  | LA                                                                                                                                                                                                                        | case   mgr- Bernadette Maloles,RN                                        | 323-783-8950                                   |                                       |                                        |
|                                                    | Yun Sun Lee (peds interest)                                                                 | RIV                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **ENDOCRINE**                                      | Ruvdeep "HAPPY" Randhawa                                                                    | RIV                                                                                                                                                                                                                       | 951-774-8198(pg), 951-858-8641©                                          | 8-258-5503                                     | 8-258-5586                            | Jen Cortez x5404                       |
|                                                    | -health educator                                                                            | Van   Buren                                                                                                                                                                                                               | Sherri Pinero or Stephanie Cullingford                                   |                                                |                                       |                                        |
|                                                    | Alan B. Cortez                                                                              | OC                                                                                                                                                                                                                        | 714-387-1284(pg), 714-356-6510(c)                                        | 8-230-2725                                     | 8-230-2738(714-254-)                  |                                        |
|                                                    | Joshua May                                                                                  | LA                                                                                                                                                                                                                        | 323-341-8755                                                             | 8-363-7120                                     |                                       |                                        |
|                                                    | Robert Itami                                                                                | PC                                                                                                                                                                                                                        | 818-373-3086                                                             |                                                |                                       |                                        |
|                                                    | Audrey Briscoe                                                                              | BF/Imperial                                                                                                                                                                                                               | 562-272-5091, 714-615-4890                                               | 562-657-4934                                   | 562-657-4622                          |                                        |
|                                                    | Benjamin Fass                                                                               | WLA                                                                                                                                                                                                                       | 323-857-2500                                                             |                                                |                                       |                                        |
|                                                    | Melanie Shim                                                                                | So.Bay/BP                                                                                                                                                                                                                 | 310-797-0413                                                             |                                                |                                       |                                        |
|                                                    | Jody Krantz                                                                                 | WH                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Alan Herschenfeld                                                                           | WH                                                                                                                                                                                                                        | 818-413-2863                                                             |                                                |                                       |                                        |
|                                                    | Parul Patel                                                                                 | SD                                                                                                                                                                                                                        | 847-708-6298                                                             | 858-573-5440                                   | 858-573-5533                          |                                        |
|                                                    | Robert Clemons                                                                              | SD                                                                                                                                                                                                                        | 619-528-5000 (operator)                                                  |                                                |                                       |                                        |
|                                                    | Jyotsna Keni                                                                                |                                                                                                                                                                                                                           | 909-437-9900(cell)                                                       |                                                |                                       |                                        |
|                                                    | Larry Wettereau                                                                             |                                                                                                                                                                                                                           | 626-245-8116(pg), 818-694-8408©                                          |                                                | 8-370-6685(626-851-)                  |                                        |
|                                                    | Zohreh Shoar                                                                                | FON                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    | Ramin Moghaddas                                                                             | FON                                                                                                                                                                                                                       | 909-458-7412                                                             | 8-250-2072                                     | 8-250-4400                            |                                        |
|                                                    | Maria Lin                                                                                   | FON   LA RIV OC                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **PEDS ENT**                                       | Carolyn V. Nguyen                                                                           | LA                                                                                                                                                                                                                        | 323-783-1858                                                             |                                                |                                       |                                        |
|                                                    | MIGUEL KRISHNAN                                                                             | RIV                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    | Robert Barretto                                                                             | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **GENETICS**                                       | Sayed Ahmed                                                                                 | RIV                                                                                                                                                                                                                       | 951-774-7202, 248-990-3666                                               | 8-258-4393                                     | 8-258-5320                            |                                        |
|                                                    | Trevor Hoffman                                                                              | FON/WLA                                                                                                                                                                                                                   | 949-233-8099                                                             | 8-250-5993                                     | 8-390-2368, 8-250-4055                |                                        |
|                                                    | Diane Broome                                                                                | OC                                                                                                                                                                                                                        | 714-387-1637                                                             |                                                |                                       |                                        |
|                                                    | Rosetta Hassan                                                                              | BP                                                                                                                                                                                                                        | 562-262-4183, 562-755-9620                                               |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **GI**                                             |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    | Alauna Cheng                                                                                | FON                                                                                                                                                                                                                       | 909-209-1759                                                             |                                                |                                       |                                        |
|                                                    | William Mow                                                                                 | OC                                                                                                                                                                                                                        | 714-387-3249(pg)                                                         | 714-279-4269                                   | 714-279-4896                          |                                        |
|                                                    | Bruce Grill(Tue-Wed)                                                                        | FON/RIV                                                                                                                                                                                                                   | 909-209-0828                                                             | 8-258-5503                                     | 8-258-3463                            | Nicole Hutson x5464                    |
|                                                    | Mun-Wah Ng                                                                                  | FON                                                                                                                                                                                                                       | 909-209-1937(pg)                                                         | 8-250-4400                                     |                                       | or,   Carianne Ferraro                 |
|                                                    | Fred Watanabe                                                                               | LA                                                                                                                                                                                                                        | 323-279-2714                                                             |                                                | 323-783-3383                          |                                        |
|                                                    | Steven Kim                                                                                  | LA                                                                                                                                                                                                                        | 323-699-6694                                                             |                                                | 323-783-5351                          |                                        |
|                                                    | James Tipton                                                                                | PC                                                                                                                                                                                                                        | 818-323-1150                                                             | 818-375-4250                                   | 818-375-4264                          |                                        |
|                                                    | Glenn Duh                                                                                   | BF                                                                                                                                                                                                                        | 310-687-0673                                                             | 8-327-2479                                     | 562-657-2789                          |                                        |
|                                                    | Warren Shapiro                                                                              | SD                                                                                                                                                                                                                        |                                                                          | 8-240-6150                                     |                                       |                                        |
| -Peds nutritionist                                 | Stefanie Cullingford                                                                        | RIV                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **HEM/ONC**                                        | Vaghasia,Neha                                                                               | FON                                                                                                                                                                                                                       | 909-209-1250(pg)                                                         | 8-250-6126                                     |                                       |                                        |
|                                                    | Kenji Morimoto                                                                              | FON                                                                                                                                                                                                                       | 909-209-1508                                                             | 8-250-6126                                     | 8-250-5844                            |                                        |
|                                                    | Liesl Mathias                                                                               | FON                                                                                                                                                                                                                       | 909-370-7632                                                             | 8-250-6126, 8-220-4824                         | 8-250-7069                            |                                        |
|                                                    | Naveen Qureshi                                                                              | OC                                                                                                                                                                                                                        | 562-272-5136                                                             | 8-220-4824                                     |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **ID**                                             | Roopa Viraraghavan                                                                          | OC                                                                                                                                                                                                                        | 714-423-0485                                                             |                                                |                                       |                                        |
|                                                    | Zachary Taylor                                                                              | LA                                                                                                                                                                                                                        | 323-279-0378                                                             |                                                | 8-363-1530(5350)                      |                                        |
|                                                    | Gary Burkhart                                                                               | LA                                                                                                                                                                                                                        | 323-341-1265                                                             | 8-363-5350                                     | 8-363-7274                            |                                        |
|                                                    | Evan Steinberg                                                                              | LA                                                                                                                                                                                                                        | 323-279-0496                                                             | 8-363-5350                                     | 8-363-5948(5350)                      |                                        |
|                                                    | Victor K. Wong                                                                              | DOW                                                                                                                                                                                                                       | 310-609-6257                                                             | 8-327-2216                                     | 8-327-2310                            |                                        |
|                                                    | David Bronstein                                                                             | PALMDALE                                                                                                                                                                                                                  | 661-225-6306(pg)   310-498-01669(cell)                                   |                                                | 8-359-7823(661-533-)                  |                                        |
|                                                    | Margaret Khoury                                                                             | BP                                                                                                                                                                                                                        | 626-245-0043(pg)                                                         |                                                | 8-370-6833(626-851-)                  |                                        |
|                                                    | Kaeryn Lewis                                                                                | PC                                                                                                                                                                                                                        | 818-323-2667                                                             | 8-350-2542                                     | 8-350-3963(2542)                      |                                        |
|                                                    | Bradley Ackerson                                                                            | SB                                                                                                                                                                                                                        | 310-563-0421                                                             |                                                | 8-341-2208                            |                                        |
|                                                    | Mark Salzman                                                                                | WLA                                                                                                                                                                                                                       | 323-857-2500   ex.2147                                                   | 8-390-3088                                     | 8-390-3089                            |                                        |
|                                                    | Mark Sawyer                                                                                 | SD                                                                                                                                                                                                                        |                                                                          | 8-240-6170                                     |                                       |                                        |
|                                                    | Kevin Quinn                                                                                 | FON/RIV                                                                                                                                                                                                                   | 909-209-1343                                                             |                                                | 8-250-5837                            | 909-427-5408                           |
|                                                    | Sean Fitzwater                                                                              | LA                                                                                                                                                                                                                        | 323-854-9213                                                             |                                                |                                       | (ID clinic direct)                     |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **METABOLIC**                                      | Divya Vats(male)<br/>Moin Vera                                                                            | LA                                                                                                                                                                                                                        | 323-819-2978(cell), 213-230-0256(pg)                                     | Barbara Lyons, RN                              | 323-783-6970 (preferred)                         | Barbara Lyons,RN                       |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          | 323-783-6970   (tie line 363) 323-783-3708(VM) |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **NEPHROLOGY**                                     | Maria Domingo                                                                               | FON                                                                                                                                                                                                                       |                                                                          | 8-250-5454                                     |                                       | check on call app under   Fontana      |
|                                                    | James Tong                                                                                  | FON                                                                                                                                                                                                                       | 909-209-1307                                                             | 8-250-6126                                     | 8-250-5847                            |                                        |
|                                                    | Rita Sheth (part time)                                                                      | OC                                                                                                                                                                                                                        | 714-387-3840(pg)                                                         | 8-235-5643                                     | 949-262-5649                          |                                        |
|                                                    | Gale Gordon                                                                                 | LA                                                                                                                                                                                                                        | 310-286-4240                                                             | 323-783-5351                                   | 323-783-5321                          |                                        |
|                                                    | Margarett Hsiau                                                                             | LA                                                                                                                                                                                                                        | 323-699-7368(pg)                                                         | 310-384-6141(c)                                | 562-657-3168(DOW)                     | 714-430-2600(Tustin)                   |
|                                                    | Beatriz Kuizon                                                                              | LA                                                                                                                                                                                                                        | 323-341-2431                                                             | 8-363-4205                                     | 8-363-1125                            |                                        |
|                                                    | Robert Mak                                                                                  | SD                                                                                                                                                                                                                        |                                                                          | 8-240-6170                                     |                                       |                                        |
|                                                    | Elizabeth Ingullie                                                                          | SD                                                                                                                                                                                                                        |                                                                          | 8-240-6170                                     |                                       |                                        |
|                                                    | Joel Hernandez                                                                              |                                                                                                                                                                                                                           | 323-699-6846(pg)                                                         |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **NEUROLOGY**                                      | Gamil Fteeh                                                                                 | RIV                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    | Yawen Wang                                                                                  | BP                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Rita Marshall                                                                               | RIV/FON                                                                                                                                                                                                                   | 909-209-2801(pg)                                                         | 8-258-4747                                     | 909-782-9806                          |                                        |
|                                                    | Tracy Chiem                                                                                 | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Susan Skinner                                                                               | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Suresh Gurbani                                                                              | OC                                                                                                                                                                                                                        |                                                                          |                                                | 8-215-2255/2321/2251                  |                                        |
|                                                    | Krisin Lueck                                                                                | OC                                                                                                                                                                                                                        |                                                                          | 714-830-6518                                   |                                       |                                        |
|                                                    | Benjamin Spurgeon                                                                           | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Nirmala "Dr. Nathan" Gowrinathan                                                            | LA                                                                                                                                                                                                                        |                                                                          | 8-363-4688                                     |                                       |                                        |
|                                                    | Dean Sarco                                                                                  | LA                                                                                                                                                                                                                        | 323-279-1784(pg)                                                         |                                                | 323-783-4200                          |                                        |
|                                                    | David Shaw                                                                                  | HC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Richard Kaplan                                                                              | SD                                                                                                                                                                                                                        |                                                                          | 8-240-6580                                     |                                       |                                        |
|                                                    | Kian Yu                                                                                     | FON                                                                                                                                                                                                                       | 909-209-1105(pg)                                                         | 8-250-5441                                     | 8-250-4166                            |                                        |
|                                                    | Shelly Bose                                                                                 | DOW                                                                                                                                                                                                                       |                                                                          | 8-327-2696                                     | 562-657-2696                          |                                        |
|                                                    | Gamil Fteeh                                                                                 | FON                                                                                                                                                                                                                       | TH&FR IN RIV                                                             |                                                |                                       |                                        |
| -neuromuscular sp                                  | Abel Wu                                                                                     |  LA                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| ** NEUROSURGERY**                                  | Mark Calayag                                                                                | FON                                                                                                                                                                                                                       | 909-427-7777   x2076                                                     | 8-250-7278                                     | 8-250-4570                            |                                        |
|                                                    |                                                                                             | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Darian Esfahani                                                                             | LA                                                                                                                                                                                                                        | 323-279-1691(pg)                                                         | 323-854-9235                                   |                                       |                                        |
|                                                    | Greg Gerras                                                                                 | SD                                                                                                                                                                                                                        |                                                                          | 8-280-5511                                     |                                       |                                        |
| ***   spina bifida clinic                          | Fedor Hauptman                                                                              | LA                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Christens                                                                                   |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **NUTRITIONIST**                                   |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **PEDS OPHTHALMOLOGY**                             | Jonathan Duerksen                                                                           | FON-Rancho   Cu.                                                                                                                                                                                                          |                                                                          | 909-477-3821                                   | 8-239-3808                            |                                        |
|                                                    | Ashish Mehta                                                                                | OC-Yorba   Linda                                                                                                                                                                                                          |                                                                          | 8-217-3663                                     |                                       |                                        |
|                                                    | Tu Lan Nhat,Nguyen                                                                          | FON                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    | Naomi Ellenhorn                                                                             | LA                                                                                                                                                                                                                        | 310-795-4544                                                             | 323-783-4144                                   | 323-783-7707                          |                                        |
|                                                    | Steven Ortiz <br/> Jennifer Bee Aye                                                                                | RIV                                                                                                                                                                                                                       |                                                                          | 8-258-4717                                     | 8-258-4489 <br/> 909-973-2167                           |                                        |
|                                                    | Tinny Dinh                                                                                  | RIV                                                                                                                                                                                                                       | on call   pg 774- 7204                                                   | 8-258-4717                                     |                                       | RN-x5886   or x4723                    |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **PEDS ORTHOPEDICS**                               | Corey Fuller                                                                                | FON                                                                                                                                                                                                                       | 8-250-7777   x                                                           | 8-250-7066                                     |                                       |                                        |
|                                                    | Brent Berger                                                                                | FON                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
|                                                    | James H. Lau                                                                                | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Hillard Spencer                                                                             | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Mina Kono                                                                                   | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | John Houkom                                                                                 | SD                                                                                                                                                                                                                        |                                                                          | 8-280-5474                                     |                                       |                                        |
|                                                    | Timothy Mickel                                                                              | SD-RIV                                                                                                                                                                                                                    |                                                                          |                                                |                                       |                                        |
|                                                    | Scott Showmaker                                                                             |                                                                                                                                                                                                                           |                                                                          | 8-280-5474                                     |                                       |                                        |
| ***specialized in Sports   Orthopedics             | Marc Fogelson                                                                               | RIV                                                                                                                                                                                                                       | 951-774-8001                                                             | 8-258-4166                                     | 8-258-3938                            |                                        |
| ***sports and concussion clinic                    | Robert Sallis-Family medicine dept.                                                         | FON-sports   clinic                                                                                                                                                                                                       | 909-370-7684                                                             |                                                | 909-427-7384                          | Mary   Gonzalez, 909-609-2515          |
| ***specialized in Hand                             | Hild                                                                                        | RIV                                                                                                                                                                                                                       |                                                                          |                                                | 8-258-3253                            |                                        |
| ***sports med                                      | James Hwang                                                                                 | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
| ***for severe scoliosis                            | William   Weiser                                                                            | BP                                                                                                                                                                                                                        | ***refer to Riverside   Ortho first!!                                    |                                                |                                       |                                        |
| ***sports med                                      | Nepomuceno                                                                                  | Murrietta                                                                                                                                                                                                                 | "sports30"                                                               |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **PULMONARY**                                      | Muhammad Saeed                                                                              | LA                                                                                                                                                                                                                        | 323-699-7812                                                             |                                                | 323-783-5320                          | Martha (CF clinic),   8-363-1291       |
|                                                    | Eugene   Sohn                                                                               | LA                                                                                                                                                                                                                        | 323-279-8836, 323-783-5350                                               |                                                |                                       |                                        |
|                                                    | Stephen   Johnson                                                                           | LA                                                                                                                                                                                                                        | 323-918-1874                                                             |                                                | 323-783-6057                          |                                        |
|                                                    | Henry   Wojtczak                                                                            | SD                                                                                                                                                                                                                        |                                                                          | 8-240-6170                                     |                                       |                                        |
|                                                    | Kyle   McCallin                                                                             | FON                                                                                                                                                                                                                       |                                                                          |                                                |                                       |                                        |
| ***sleep medicine                                  | Dennis Hwang                                                                                | FON                                                                                                                                                                                                                       |                                                                          |                                                | 8-250-7260                            |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **CHILD   PSYCHIATRY**                             | Catherine   Stinnett                                                                        | CORONA                                                                                                                                                                                                                    |                                                                          | 8-262-7148                                     |                                       |                                        |
|                                                    | Mehran Motamed                                                                              | CORONA                                                                                                                                                                                                                    |                                                                          | 8-262-7148                                     |                                       |                                        |
|                                                    | Zehzaa Mikhaeli                                                                             | RIV-Canyon   Crest                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Bernard Nana-Diego                                                                          | RIV-Canyon   Crest                                                                                                                                                                                                        |                                                                          | 8-257-4050                                     | 8-257-4021                            |                                        |
|                                                    | Evita Rocha                                                                                 | RIV-Canyon   Crest                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
| **NEUROPSYCH TEST                                  | REFER   TO OC (PSYCH)                                                                       |                                                                                                                                                                                                                           | Dr.Priscilla Armstrong                                                   |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **RHEUMATOLOGY**                                   | Mina Chaudhari                                                                              | FON/OC/RIV- TH                                                                                                                                                                                                            | 909-209-1846, 714-264-8931                                               | 8-250-5451                                     | 8-250-6245                            | Jennifer   Cortes x5404                |
|                                                    | Judith Garza                                                                                | LA                                                                                                                                                                                                                        | 323-341-1296, 626-482-9641                                               | 323-783-5166                                   | 323-783-1997   or x5310               |                                        |
|                                                    | Anusha   Ramanathan                                                                         | LA/Downey                                                                                                                                                                                                                 | 562-272-6139(pg)                                                         |                                                |                                       |                                        |
|                                                    | Rhina   Castillo                                                                            | OC/FON                                                                                                                                                                                                                    |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **PEDS   SURGERY**                                 | Stanley   T. Lau                                                                            | OC/DOW                                                                                                                                                                                                                    | 323-699-2010, 714-227-1333                                               |                                                |                                       |                                        |
|                                                    | Roman   Sydorak                                                                             | LA/FON                                                                                                                                                                                                                    | 323-699-7612, 323-219-6465                                               |                                                | 323-783-7507, 909-427-5172            | Fontana   Surgery Clinic, 909-609-2008 |
|                                                    | Albert   Chong                                                                              | LA/FON                                                                                                                                                                                                                    | 323-493-6943                                                             |                                                |                                       | 8-250-3688 (scheduler)                 |
|                                                    | Donald B. Shaul                                                                             | LA/DOW                                                                                                                                                                                                                    | 323-699-7598, 818-667-2619                                               |                                                | 323-783-4857                          | Jamila Dainty,   323-783-5456          |
|                                                    | W. David Vazquez                                                                            | SD                                                                                                                                                                                                                        | 619-682-8049, 858-229-4512                                               | 619-528-6746                                   | 619-528-5694                          |                                        |
|                                                    | Cindy   Tai                                                                                 | FON                                                                                                                                                                                                                       | 323-699-0601(pg)                                                         |                                                |                                       |                                        |
| -also   see pectus                                 | Ed Yoo                                                                                      | LA/FON/RIV                                                                                                                                                                                                                | 323-699-0523, 215-498-8240                                               | 2nd/4th   Wed-pm                               |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Maxillofacial   SURGERY                            | David Bell                                                                                  | OC                                                                                                                                                                                                                        | 714-644-2068, 714-387-1501                                               |                                                |                                       |                                        |
|                                                    | Randal Schoeman                                                                             | OC                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Alexander   Kim                                                                             | SD                                                                                                                                                                                                                        |                                                                          | 619-528-2597, 760-591-4276                     |                                       |                                        |
| **PEDS   DENTISTRY**                               | James   Richardson, DDS                                                                     | Corona                                                                                                                                                                                                                    | 951-735-2011                                                             |                                                | for kids   needing general anesthesia |                                        |
| ***for STAT outside referral (such as Mandible FX) | Dr.   Stringer                                                                              | Outside   referral                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **CARDIOTHORACIC SURGERY**                         | Lawrence   Kong                                                                             | FON                                                                                                                                                                                                                       | 909-872-5135                                                             | 909-427-6060                                   | 909-427-5768                          |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **PEDS   UROLOGY**                                 | Jennifer   Yiee                                                                             | OC                                                                                                                                                                                                                        | 714-387-3774(pg), 310-254-7766(cell)                                     |                                                | 8-215-7530                            |                                        |
|                                                    | Huang                                                                                       | LA                                                                                                                                                                                                                        |                                                                          |                                                |                                       |                                        |
|                                                    | Monica Metzdorf                                                                             | LA                                                                                                                                                                                                                        | 323-341-1401                                                             |                                                | 323-783-5426                          |                                        |
|                                                    | Ethan Franke                                                                                | SD                                                                                                                                                                                                                        | 619-682-9480(pg)                                                         | 619-516-6362                                   |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **CHOC   OPERATOR**                                | 714-997-3000                                                                                |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **RIVERSIDE OPERATOR**                             | 8-258-2000                                                                                  |                                                                                                                                                                                                                           | Direct line x3945                                                        |                                                |                                       |                                        |
| -spanish operator                                  | 8-288-1050                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -admitting DOD                                     |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -peds   floor                                      |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -ER                                                |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -NICU                                              |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -admitting office                                  | 8-258-3094                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **FONTANA OPERATOR**                               | 909-427-5000 (8-332)                                                                        |                                                                                                                                                                                                                           | Direct 8-250-7373                                                        |                                                |                                       |                                        |
| -admitting Resident                                | 8-250-7777   x1224                                                                          |                                                                                                                                                                                                                           | Attending(pg)x1223                                                       |                                                |                                       |                                        |
| -peds   floor                                      | 8-332-9450                                                                                  | x7874                                                                                                                                                                                                                     |                                                                          |                                                |                                       |                                        |
| -peds   floor charge nurse                         | 8-332-7882                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -PICU                                              | 8-332-9445                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -PICU   attending                                  | 8-332-7777   x3966                                                                          |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -PICU   charge nurse                               | 8-332-4448                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -referral   scheduler                              | Cindy                                                                                       |                                                                                                                                                                                                                           | 8-332-4400                                                               |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **ANAHEIM OPERATOR**                               | 8-215-2000                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -ER                                                | 8-215-2800                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -peds   floor                                      | 8-220-4573                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -peds   admitting MD                               | 714-387-1042                                                                                |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **SUNSET OPERATOR**                                | 8-363-4011                                                                                  |                                                                                                                                                                                                                           | 800-954-8000??                                                           |                                                |                                       |                                        |
| -NICU                                              | 8-363-4285, 323-783-9411                                                                    |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -PICU                                              | 323-783-9541                                                                                |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -PICU   charge nurse                               | 323-783-6923 x0923                                                                          |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -peds   floor                                      | 8-363-5350                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -DOD   pager                                       | 323-279-PEDS(7337)                                                                          |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Riverside Radiology                                | Annie Lee                                                                                   | x4179                                                                                                                                                                                                                     | Hoon Kang                                                                | x5597                                          | Andrew Song                           |                                        |
|                                                    | Tran                                                                                        | x4613                                                                                                                                                                                                                     | Heather   Lei                                                            | x5534                                          | Richard   Cho                         |                                        |
|                                                    | George Hsia                                                                                 | x4018                                                                                                                                                                                                                     | Houng                                                                    |                                                | Pouyan Golshani                       | x3188                                  |
|                                                    | Bo Gyi                                                                                      | x4014                                                                                                                                                                                                                     | Alice Chan                                                               |                                                | Christina   Lee                       | x4017                                  |
|                                                    | Allison   Yee                                                                               | x4019                                                                                                                                                                                                                     | Chan Chang                                                               |                                                | Jimmy Ton                             |                                        |
|                                                    | Danny Chang                                                                                 | x4016                                                                                                                                                                                                                     | Ricky Kim                                                                | x5380                                          | Quan Tran                             |                                        |
|                                                    | Peter Wong                                                                                  | x4955                                                                                                                                                                                                                     | Edgar Lai                                                                | x3508                                          | Agustinus   Suhardia                  |                                        |
|                                                    | Danh Le                                                                                     | x4013                                                                                                                                                                                                                     | Aarti Kaushik                                                            |                                                |                                       |                                        |
|                                                    | Khanh Nguyen                                                                                | x4013                                                                                                                                                                                                                     | Vaishali   Patel                                                         |                                                |                                       |                                        |
| -ultrasound                                        | x4448                                                                                       |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Fontana Radiology(for MRI sedation)                | Valerie   Velarde                                                                           | 8-250-4461                                                                                                                                                                                                                |                                                                          |                                                |                                       |                                        |
|                                                    | 1. Order   MRI as usual but state "With sedation in Fontana" in comment   section           | 2.   Within 30 days of MRI date, you must do pre- procedure clearance PE. Make   sure to obtain consent. Document patient "cleared for sedation" and   "benefit and risk of sedation discussed and consent to anesthesia" | 3.   Sedation order and inpatient H&P done by Fontana MD                 |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| **RIVERSIDE ORTHOPEDICS**                          |                                                                                             |                                                                                                                                                                                                                           | RIVERSIDE   ORTHO PA                                                     |                                                |                                       |                                        |
| -reception                                         | 8-258-4645                                                                                  |                                                                                                                                                                                                                           | Delanka   Silva                                                          |                                                | John Miller                           | Brian Redding                          |
| -ortho   RN                                        | x4406,   x4811, x4795                                                                       |                                                                                                                                                                                                                           | Lance Farr                                                               |                                                | Huey Nguyen                           | Kimberly Adams                         |
| -cast   room                                       | x4689                                                                                       |                                                                                                                                                                                                                           | Milan Vora                                                               |                                                | Kim Dooda                             |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           | Nick Carnahan                                                            |                                                | Lu Jallamilio                         |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           | Patricia Mcdougall                                                       |                                                | Ty   Roseberry                        |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           | Jared Robertson                                                          |                                                | Pat Duke                              |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| OPHTHALMOLOGY RN for stat consultation             | x4723 (Beena)                                                                               |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| ADULT IDDM Coordinator                             | Marjerie Barr                                                                               | x4807                                                                                                                                                                                                                     |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| PEDS   MED ADVICE                                  | x4354, x3112                                                                                |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| AUDIOLOGY DEPT                                     | x4741                                                                                       |                                                                                                                                                                                                                           | SPEECH   DEPT                                                            | x4759                                          | PEDS   OT-RIV                         | Rebekah   Vasquez                      |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| OUTSIDE REFERRAL                                   | 8-265-4294                                                                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    | password expires in 90   days. must call Physician Help Desk, 8- 338-7395                   |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| INLAND REGIONAL CTR                                | 909-890-3370(under 3)                                                                       | 909-890-4711(over 3)                                                                                                                                                                                                      |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| KP professional recuitment                         | Robert Gonzalez                                                                             | 626-405-5861                                                                                                                                                                                                              |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| PEDS   master scheduler                            |                                                                                             | 8-286-2630                                                                                                                                                                                                                |                                                                          |                                                |                                       |                                        |
| PEDS schedule coord.                               | Joanne Alvarez                                                                              | 8-258-4301                                                                                                                                                                                                                |                                                                          |                                                |                                       |                                        |
| EEG   scheduler                                    | RIVERSIDE                                                                                   | 8-286-2635                                                                                                                                                                                                                |                                                                          |                                                |                                       |                                        |
|                                                    | FONTANA                                                                                     | 8-250-5430                                                                                                                                                                                                                |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| KITS   coordinator                                 | Cora Carnero                                                                                | 8-258-4094                                                                                                                                                                                                                |                                                                          |                                                |                                       |                                        |
| CCS   coordinator                                  | Erica Lee                                                                                   | 626-381-4347                                                                                                                                                                                                              |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| MEMBERSHIP service                                 | 8-398-4400                                                                                  |                                                                                                                                                                                                                           | x4571   (administrator)                                                  |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| DME(Fontana)                                       | 1-855-80-KPDME   (57363)                                                                    |                                                                                                                                                                                                                           | M-F   8:30-6, SAT 8:30-5                                                 |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Dermatology Cosmetic Clinic                        | 562-803-1331                                                                                | self referral                                                                                                                                                                                                             |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| CIRCUMCISION -under 30   days old                  | Forward note to P_5000052 (OBGRIRIV CALL   CENTER POOL) and P_18827 (OBGRIRIV RN)           | Gema   Castellon, RN x4029                                                                                                                                                                                                | Document   in note, "cleared for circumcision"                           | make   sure recieved Vit. K                    |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| teleconference for outside                         | 1-888-858-2133                                                                              | 8362299#                                                                                                                                                                                                                  |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Regional Asthma Hotline                            | 877-4KP-ASTHMA or 877-457-2784                                                              |                                                                                                                                                                                                                           | useful #   to give to patient. 24-7 oncall RN coverage                   |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Pharmacy   New Member Program Service(PNMP)        | if 5 or more Rx from   outside, call this #. They will convert Rx to our formulary for you. |                                                                                                                                                                                                                           | Julie   Yonemitsu, Pharm D. 951- 774-8131(pg)                            |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| KP   LEGAL COUNSEL                                 | Roxana   Yoonessi MD JD                                                                     | 8-335-5725                                                                                                                                                                                                                | (1-626-405-)                                                             | 818-321-9242 (cell)                            |                                       |                                        |
|                                                    | Hema Anwar JD                                                                               |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| TMJ   PAIN                                         | refer   patient to physical medicine dept. first, not ENT.                                  |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Director   of Bioethics                            | Dan Wilson                                                                                  | 951-204-3437                                                                                                                                                                                                              | 661-706-2523                                                             |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| CARDIAC ECHO                                       | do   referral to cardiology (adult)                                                         |                                                                                                                                                                                                                           | click   'reason' box to chose option for pediatric echo without sedation | chose   'yes' on authoriztion                  |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Frenotomy                                          | Refer to ENT (Dr. Krishnan)                                                                 | or call                                                                                                                                                                                                                   | Malu Lungay                                                              | 8-258-5998/4737                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| DENTIST with KP previledge   for anesthesia        | Richard   Kunihara,DDS                                                                      | Upland                                                                                                                                                                                                                    | 909-985-5117                                                             |                                                |                                       | 360 East 7th st. suite J               |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| -give outside referral dept #                      | Harvey   Lee, DDS                                                                           | Irvine                                                                                                                                                                                                                    | 949-733-3433                                                             | Under   DentiCal                               |                                       |                                        |
|                                                    | Smile   Wide Dental                                                                         | Costa Mesa                                                                                                                                                                                                                | 949-548-5588                                                             |  Under DentiCal                                |                                       |                                        |
|                                                    | James Richardson,DDS                                                                        | Corona                                                                                                                                                                                                                    | 951-735-2011                                                             |                                                |                                       |                                        |
|                                                    | Hilo, DDS                                                                                   | thru Mobi                                                                                                                                                                                                                 |                                                                          | Under Medical                                  |                                       |                                        |
| peds   nutritionist                                | Heidy   Patterson, Stefanie Cullingford                                                     | Joyce   Atkins                                                                                                                                                                                                            | Sherry Pinero                                                            |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| NB   screening contact                             | 844-343-9372                                                                                |                                                                                                                                                                                                                           | Kara Brink, RN (Pasadena)                                                | 626-564-3322                                   | (8-338)                               |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Travel Advisory                                    | 1-800-517-5556(for patient)                                                                 |                                                                                                                                                                                                                           | 8-295-6111(back line)                                                    |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| RSV   synergis protocol                            | Robyn Gerome                                                                                |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Speech                                             | Alejandrina   Siriban Ann Bendroff                                                          |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Jennifer Cortes                                    | x5404                                                                                       |                                                                                                                                                                                                                           | Sophie Gonzalea                                                          | x5464                                          |                                       |                                        |
| -Endo                                              |                                                                                             |                                                                                                                                                                                                                           | -GI                                                                      |                                                |                                       |                                        |
| -Rhumatology                                       |                                                                                             |                                                                                                                                                                                                                           | -Cardio                                                                  |                                                |                                       |                                        |
| -Asthma                                            |                                                                                             |                                                                                                                                                                                                                           | -HRIF                                                                    |                                                |                                       |                                        |
| -ID                                                |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
|                                                    |                                                                                             |                                                                                                                                                                                                                           |                                                                          |                                                |                                       |                                        |
| Physical Therapy for positional plagiocephaly      | Jody Wright                                                                                 |                                                                                                                                                                                                                           | Loan Nugyen                                                              | send   referral as young as 2mo old,           | Dr.   Arambulo after 6mo old          |                                        |

<br/>
<br/>

{{< pagebreak >}}

## Pediatric Subspecialty Consultation {#sec-subspecialty-consult}

### Cardiology:

- Eugene Hwang: eugene.y.hwang@kp.org
- Chriselle Ebreo: chrisellemae.n.ebreo@kp.org
- Vanessa Ogueri: vanessa.x.ogueri@kp.org

### Craniofacial Team:

- Dr. Trevor Hoffman
  - +1-949-233-8009 (team contact)
  - +1-323-857-2368 (clinic)

