<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Respiratory – KP Riverside Neonatal ICU Manual</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./cardiovascular.html" rel="next">
<link href="./death-workflows.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ab9a0a4e0698b5410a6d6c29fb8c72b9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./respiratory.html">System-Based Protocols</a></li><li class="breadcrumb-item"><a href="./respiratory.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Respiratory</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">NICU Manual</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">&nbsp;</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">NICU Operations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./telemedicine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Telemedicine</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./phone-numbers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Phone Numbers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Physician Operations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./publications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Research/QI activities</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">General Care</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./admission.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">NICU Admission</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./transfer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Transfer an Infant Out</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discharge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Discharging an Infant</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./documentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Documentation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./death-workflows.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Fetal and Neonatal Death Workflows and Documentation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">System-Based Protocols</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./respiratory.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Respiratory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cardiovascular.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Cardiovascular</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nutrition-fluid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Nutrition, Fluid and Electrolytes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gastrointestinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Gastroenterology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./renal-urology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Nephrology &amp; Urology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./infectious-disease.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Infectious Disease</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./endocrine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Endocrinology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./neurology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Neurology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hemonc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Hematology &amp; Oncology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./genetics-lluch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Genetic Disorders (LLUCH NICU Manual)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Special Considersations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./periviability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Periviability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./VLBW.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">VLBW/ELGAN/ELBW Infants</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Delivery Room Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./surgical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Surgical/Derm/Ophtho Considerations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Health Maintenance</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vaccine.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Vaccine schedule</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lluch-formulary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">LLUCH NICU Formulary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dotPhrases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Dot Phrases</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#least-invasive-surfactant-administration" id="toc-least-invasive-surfactant-administration" class="nav-link active" data-scroll-target="#least-invasive-surfactant-administration"><span class="header-section-number">10.1</span> Least Invasive Surfactant Administration</a>
  <ul class="collapse">
  <li><a href="#indication" id="toc-indication" class="nav-link" data-scroll-target="#indication">Indication</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">Procedure</a></li>
  </ul></li>
  <li><a href="#respiratory-support-guide" id="toc-respiratory-support-guide" class="nav-link" data-scroll-target="#respiratory-support-guide"><span class="header-section-number">10.2</span> Respiratory Support Guide</a>
  <ul class="collapse">
  <li><a href="#sec-bCPAP" id="toc-sec-bCPAP" class="nav-link" data-scroll-target="#sec-bCPAP">Bubble CPAP (bCPAP)</a></li>
  <li><a href="#sec-elgan-elbw-resp-protocol" id="toc-sec-elgan-elbw-resp-protocol" class="nav-link" data-scroll-target="#sec-elgan-elbw-resp-protocol">ELGAN/ELBW Respiratory Support Protocol for the First 72 Hrs</a></li>
  </ul></li>
  <li><a href="#sec-nava" id="toc-sec-nava" class="nav-link" data-scroll-target="#sec-nava"><span class="header-section-number">10.3</span> Neurally adjusted ventilatory assist (NAVA)</a>
  <ul class="collapse">
  <li><a href="#initial-nava-set-up" id="toc-initial-nava-set-up" class="nav-link" data-scroll-target="#initial-nava-set-up">Initial NAVA Set-Up</a></li>
  </ul></li>
  <li><a href="#high-frequency-jet-ventilator-hfjv" id="toc-high-frequency-jet-ventilator-hfjv" class="nav-link" data-scroll-target="#high-frequency-jet-ventilator-hfjv"><span class="header-section-number">10.4</span> High-Frequency Jet Ventilator (HFJV)</a>
  <ul class="collapse">
  <li><a href="#indications" id="toc-indications" class="nav-link" data-scroll-target="#indications">Indications</a></li>
  <li><a href="#initial-settings" id="toc-initial-settings" class="nav-link" data-scroll-target="#initial-settings">Initial Settings</a></li>
  <li><a href="#oxygenation-management" id="toc-oxygenation-management" class="nav-link" data-scroll-target="#oxygenation-management">Oxygenation Management</a></li>
  <li><a href="#additional-initiation-steps" id="toc-additional-initiation-steps" class="nav-link" data-scroll-target="#additional-initiation-steps">Additional Initiation Steps</a></li>
  <li><a href="#management-and-titration" id="toc-management-and-titration" class="nav-link" data-scroll-target="#management-and-titration">Management and Titration</a></li>
  <li><a href="#disease-specific-strategies" id="toc-disease-specific-strategies" class="nav-link" data-scroll-target="#disease-specific-strategies">Disease-Specific Strategies</a></li>
  <li><a href="#troubleshooting-1" id="toc-troubleshooting-1" class="nav-link" data-scroll-target="#troubleshooting-1">Troubleshooting</a></li>
  <li><a href="#dot-phrases" id="toc-dot-phrases" class="nav-link" data-scroll-target="#dot-phrases">Dot-phrases</a></li>
  </ul></li>
  <li><a href="#sec-extubation" id="toc-sec-extubation" class="nav-link" data-scroll-target="#sec-extubation"><span class="header-section-number">10.5</span> Extubation Workflow for ELGAN/ELBW</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a></li>
  <li><a href="#timing-of-successful-extubation-in-elganelbw-from-different-studies" id="toc-timing-of-successful-extubation-in-elganelbw-from-different-studies" class="nav-link" data-scroll-target="#timing-of-successful-extubation-in-elganelbw-from-different-studies">Timing of successful extubation in ELGAN/ELBW from Different Studies</a></li>
  <li><a href="#checklist" id="toc-checklist" class="nav-link" data-scroll-target="#checklist">Checklist</a></li>
  <li><a href="#procedures" id="toc-procedures" class="nav-link" data-scroll-target="#procedures">Procedures</a></li>
  <li><a href="#what-to-expect-after-extubation" id="toc-what-to-expect-after-extubation" class="nav-link" data-scroll-target="#what-to-expect-after-extubation">What to expect after extubation</a></li>
  </ul></li>
  <li><a href="#cardiopulmonary-events---spells" id="toc-cardiopulmonary-events---spells" class="nav-link" data-scroll-target="#cardiopulmonary-events---spells"><span class="header-section-number">10.6</span> Cardiopulmonary Events - Spells</a>
  <ul class="collapse">
  <li><a href="#regional-definition" id="toc-regional-definition" class="nav-link" data-scroll-target="#regional-definition">Regional Definition</a></li>
  <li><a href="#types-of-bd-spells" id="toc-types-of-bd-spells" class="nav-link" data-scroll-target="#types-of-bd-spells">Types of B/D spells</a></li>
  <li><a href="#bedside-practice-update" id="toc-bedside-practice-update" class="nav-link" data-scroll-target="#bedside-practice-update">Bedside Practice Update</a></li>
  <li><a href="#sec-protocol-sleep-spells-monitoring" id="toc-sec-protocol-sleep-spells-monitoring" class="nav-link" data-scroll-target="#sec-protocol-sleep-spells-monitoring">Sleep spells monitoring</a></li>
  <li><a href="#sec-protocol-feeding-spells-monitoring" id="toc-sec-protocol-feeding-spells-monitoring" class="nav-link" data-scroll-target="#sec-protocol-feeding-spells-monitoring">Feeding spells monitoring</a></li>
  <li><a href="#spell-watch-after-hepatitis-b-vaccine-administration" id="toc-spell-watch-after-hepatitis-b-vaccine-administration" class="nav-link" data-scroll-target="#spell-watch-after-hepatitis-b-vaccine-administration">Spell watch after Hepatitis B vaccine administration</a></li>
  <li><a href="#sleep-study" id="toc-sleep-study" class="nav-link" data-scroll-target="#sleep-study">Sleep study</a></li>
  </ul></li>
  <li><a href="#respiratory-support-weaning-algorithm" id="toc-respiratory-support-weaning-algorithm" class="nav-link" data-scroll-target="#respiratory-support-weaning-algorithm"><span class="header-section-number">10.7</span> Respiratory Support Weaning Algorithm</a></li>
  <li><a href="#diuretics-algorithm" id="toc-diuretics-algorithm" class="nav-link" data-scroll-target="#diuretics-algorithm"><span class="header-section-number">10.8</span> Diuretics Algorithm</a></li>
  <li><a href="#bronchouplmonary-dysplasia-bpd" id="toc-bronchouplmonary-dysplasia-bpd" class="nav-link" data-scroll-target="#bronchouplmonary-dysplasia-bpd"><span class="header-section-number">10.9</span> Bronchouplmonary dysplasia (BPD)</a>
  <ul class="collapse">
  <li><a href="#sec-bpd-bundle" id="toc-sec-bpd-bundle" class="nav-link" data-scroll-target="#sec-bpd-bundle">No-BPD prevention bundle (BPD Bundle)</a></li>
  <li><a href="#dart-protocol" id="toc-dart-protocol" class="nav-link" data-scroll-target="#dart-protocol">DART protocol</a></li>
  </ul></li>
  <li><a href="#pneumothorax" id="toc-pneumothorax" class="nav-link" data-scroll-target="#pneumothorax"><span class="header-section-number">10.10</span> Pneumothorax</a>
  <ul class="collapse">
  <li><a href="#needle-thoractocentesis" id="toc-needle-thoractocentesis" class="nav-link" data-scroll-target="#needle-thoractocentesis">Needle thoractocentesis</a></li>
  <li><a href="#chest-tube-placement" id="toc-chest-tube-placement" class="nav-link" data-scroll-target="#chest-tube-placement">Chest tube placement</a></li>
  </ul></li>
  <li><a href="#airway-edema" id="toc-airway-edema" class="nav-link" data-scroll-target="#airway-edema"><span class="header-section-number">10.11</span> Airway Edema</a>
  <ul class="collapse">
  <li><a href="#treatment" id="toc-treatment" class="nav-link" data-scroll-target="#treatment">Treatment</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./respiratory.html">System-Based Protocols</a></li><li class="breadcrumb-item"><a href="./respiratory.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Respiratory</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Respiratory</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="least-invasive-surfactant-administration" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="least-invasive-surfactant-administration"><span class="header-section-number">10.1</span> Least Invasive Surfactant Administration</h2>
<p><br></p>
<section id="indication" class="level3">
<h3 class="anchored" data-anchor-id="indication">Indication</h3>
<ul>
<li>FiO<sub>2</sub> ≥ 30%<br>
</li>
<li>Increased work of breathing</li>
</ul>
</section>
<section id="procedure" class="level3">
<h3 class="anchored" data-anchor-id="procedure">Procedure</h3>
<ol type="1">
<li>Remove the stylet and needle<br>
</li>
<li>With the help of laryngoscope insert the catheter 2 cm past the Vocal cords<br>
</li>
<li>Attach Capnometer via 3.0 ETT adapter and wait for color change, once color change confirmed proceed to remove the ETT adapter/ capnometer</li>
<li>Attach syringe with Surfactant and administer it over 2-3 minutes<br>
</li>
<li>After completion give 1 ml of air slowly than remove the catheter</li>
</ol>
<p><br></p>
<video with="600" height="360" controls="">
<source src="Figures/LISA_video.mp4" type="video/mp4">
</video>
<p><br> <br></p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="respiratory-support-guide" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="respiratory-support-guide"><span class="header-section-number">10.2</span> Respiratory Support Guide</h2>
<p><br></p>
<section id="sec-bCPAP" class="level3">
<h3 class="anchored" data-anchor-id="sec-bCPAP">Bubble CPAP (bCPAP)</h3>
<section id="guide" class="level4">
<h4 class="anchored" data-anchor-id="guide">Guide</h4>
<p><img src="files/CPAP_guide.png" class="img-fluid"></p>
</section>
<section id="resources" class="level4">
<h4 class="anchored" data-anchor-id="resources">Resources</h4>
<p><a href="files/CPAP_guide.pdf" target="_blank">Download CPAP Guide PDF</a></p>
<p><a href="files/bCPAP-presentation.pptx" target="_blank">Download CPAP Presentation Slides</a></p>
<p><br></p>
</section>
</section>
<section id="sec-elgan-elbw-resp-protocol" class="level3">
<h3 class="anchored" data-anchor-id="sec-elgan-elbw-resp-protocol">ELGAN/ELBW Respiratory Support Protocol for the First 72 Hrs</h3>
<section id="protocol" class="level4">
<h4 class="anchored" data-anchor-id="protocol">Protocol</h4>
<p><img src="Figures/ELGAN-ELBW-resp-protocol.png" class="img-fluid"></p>
<p><br></p>
</section>
<section id="resource" class="level4">
<h4 class="anchored" data-anchor-id="resource">Resource</h4>
<p><a href="files/ELBW-ELGAN-Respiratory-Protocol.pdf" target="_blank">Download Protocol in PDF</a></p>
<p><br> <br></p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="sec-nava" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="sec-nava"><span class="header-section-number">10.3</span> Neurally adjusted ventilatory assist (NAVA)</h2>
<section id="nava-terminology" class="level4">
<h4 class="anchored" data-anchor-id="nava-terminology">NAVA Terminology</h4>
<ul>
<li><strong>Edi</strong>: The electrical activity of the diaphragm, considered a respiratory vital sign.</li>
<li><strong>Edi-peak</strong>: The highest value of the Edi signal during a single breath.</li>
<li><strong>Edi-min</strong>: Represents the spontaneous tonic activity of the diaphragm, preventing derecruitment of alveoli during expiration.</li>
<li><strong>NAVA level</strong>: A gain factor converting the Edi signal into proportional pressure.
<ul>
<li>Higher NAVA level = more work of breathing provided by the ventilator.<br>
</li>
<li>Lower NAVA level = more work of breathing done by the patient.</li>
</ul></li>
</ul>
</section>
<section id="edi-catheter-insertion-and-positioning" class="level4">
<h4 class="anchored" data-anchor-id="edi-catheter-insertion-and-positioning">Edi Catheter Insertion and Positioning</h4>
<ol type="1">
<li>Connect the Edi module and cable.</li>
<li>Perform the Edi module function check.</li>
<li>Measure NEX (nose-ear and xiphoid) distance in cm.</li>
<li>Determine the insertion distance.</li>
<li>Dip the Edi catheter in water and insert.</li>
<li>Connect the Edi cable to catheter.</li>
<li>Verify the position in the catheter positioning screen.</li>
<li>Check the position of the Edi catheter as a feeding tube according to hospital routines.</li>
<li>Secure it to the patient, and make a note of the insertion distance.</li>
<li>Verify the position regularly.</li>
</ol>
<p><strong>Note</strong>: For neonates below 1000 g, use Edi catheter 6 Fr/49 cm.</p>
<hr>
</section>
<section id="positioning-window" class="level4">
<h4 class="anchored" data-anchor-id="positioning-window">Positioning Window</h4>
<p><img src="Figures/nava-correct-position.png" alt="Correct Position" width="300"></p>
<ul>
<li><strong>Correct position</strong>:
<ul>
<li>Look for a diminishing ECG waveform progressing from the 1st to the 4th waveform.<br>
</li>
<li>Presence of a pink color in the 2nd and 3rd waveforms (may fluctuate to the 1st and 4th waveforms at times).</li>
</ul></li>
</ul>
</section>
<section id="re-positioning" class="level4">
<h4 class="anchored" data-anchor-id="re-positioning">Re-Positioning</h4>
<p><img src="Figures/nava-too-deep.png" alt="Correct Position" width="300"></p>
<ul>
<li><strong>Too deep</strong>:
<ul>
<li>Pull out slightly.<br>
</li>
<li>P waves gradually decrease and disappear in the lower leads.<br>
</li>
<li>Dampened QRS.</li>
</ul></li>
</ul>
<p><img src="Figures/nava-too-shallow.png" alt="Correct Position" width="300"></p>
<ul>
<li><strong>Too shallow</strong>:
<ul>
<li>Insert slightly further.<br>
</li>
<li>QRS gets bigger from the top to bottom leads.</li>
</ul></li>
</ul>
<hr>
</section>
<section id="initial-nava-set-up" class="level3">
<h3 class="anchored" data-anchor-id="initial-nava-set-up">Initial NAVA Set-Up</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 23%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Parameters</strong></th>
<th><strong>NAVA/NIV NAVA</strong></th>
<th><strong>Management</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>NAVA Level</strong></td>
<td>Start with a low NAVA level (1.0-2 cmH<sub>2</sub>O/μV)</td>
<td>- Titrate to neonates’ comfort and Edi peak 10-15 μV. <br> - If comfortable and Edi peaks &lt;5 μV, decrease NAVA Level in steps of 0.5 until Edi peak values are 5-15 μV. <br> - If increased WOB and Edi peak &gt;20 μV, increase NAVA level in 0.5 increments until comfortable and Edi peaks &lt;15 μV.</td>
</tr>
<tr class="even">
<td><strong>Edi trigger</strong></td>
<td>0.5 μV</td>
<td>Avoid “artifact self-triggering” (lower number = more sensitive).</td>
</tr>
<tr class="odd">
<td><strong>Apnea time</strong></td>
<td>3-5</td>
<td>Adjust as clinically indicated (minimum rate: 2 seconds = 30 bpm; 1 second = 60 bpm).</td>
</tr>
<tr class="even">
<td><strong>Ppeak</strong></td>
<td>35-40 cmH<sub>2</sub>O <br> <strong>NOTE</strong>: Pressure limited 5 cmH<sub>2</sub>O below Ppeak alarm limit (blue alarm).</td>
<td>Set Ppeak high enough for recruiting breaths. Increase if pressure limited alarm is constant.</td>
</tr>
<tr class="odd">
<td><strong>Backup</strong></td>
<td>Activates Pressure Control mode after apnea time if patient is apneic.</td>
<td>Set PC level and RR to assure adequate ventilation.</td>
</tr>
</tbody>
</table>
<p><strong>NOTE</strong>: Set appropriate PEEP for the patient and backup settings: PC above PEEP and RR.</p>
<hr>
<section id="weaning-in-nava" class="level4">
<h4 class="anchored" data-anchor-id="weaning-in-nava">Weaning in NAVA</h4>
<ul>
<li>Decrease the NAVA level in steps of 0.3-0.5 cmH<sub>2</sub>O/μV.</li>
<li>Decrease backup settings if in backup frequently.</li>
<li>If intubated, extubate to CPAP vs.&nbsp;NIV-NAVA depending on NAVA level, PEEP, and MAP</li>
</ul>
<hr>
</section>
<section id="troubleshooting" class="level4">
<h4 class="anchored" data-anchor-id="troubleshooting">Troubleshooting</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 31%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Parameter</strong></th>
<th><strong>Investigate the Reason</strong></th>
<th><strong>Management</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>High Edi-peak &gt;20 μV</strong></td>
<td>- WOB increased</td>
<td>- Increase NAVA level, increase Ppeak alarm limit</td>
</tr>
<tr class="even">
<td></td>
<td>- Insufficient backup support</td>
<td>- Increase backup pressure</td>
</tr>
<tr class="odd">
<td></td>
<td>- Failing NIV treatment</td>
<td>- Intubate and use NAVA</td>
</tr>
<tr class="even">
<td></td>
<td>- Discomfort and Pain</td>
<td>- Consider light analgesics</td>
</tr>
<tr class="odd">
<td></td>
<td>- Edi catheter dislocated</td>
<td>- Reposition Edi catheter</td>
</tr>
<tr class="even">
<td><strong>Low Edi-peak &lt;5 μV</strong></td>
<td>- Over-assist</td>
<td>- Decrease NAVA level</td>
</tr>
<tr class="odd">
<td></td>
<td>- Poor respiratory drive</td>
<td>- Decrease backup support</td>
</tr>
<tr class="even">
<td></td>
<td>- Sedation too high</td>
<td>- Decrease sedation</td>
</tr>
<tr class="odd">
<td><strong>Edi-min consistently &gt;5 μV</strong></td>
<td>Atelectasis</td>
<td>- FiO<sub>2</sub> high: increase PEEP by 1 <br> - Patient stable: no change</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="additional-information" class="level4">
<h4 class="anchored" data-anchor-id="additional-information">Additional Information</h4>
<p>Refer to the <strong>SERVO-u/n User’s Manual</strong> for operation of the ventilator.</p>
<blockquote class="blockquote">
<p><strong>Disclaimer</strong>: The assertions stated by physicians are strictly those of the physician and do not necessarily reflect the views of Getinge. Refer to product labeling for current indications, warnings, contraindications, and precautions.<br>
+ MCV00106173 REVA EXP11/22 + MX-7334</p>
</blockquote>
<p><strong>Source</strong>: Modified from <a href="https://www.getinge.com/dam/hospital/documents/english/mcv00106173_nava_neonatal_flowchart-en-us.pdf" target="_blank">this online document</a> (Click <a href="files/mcv00106173_nava_neonatal_flowchart-en-us.pdf" target="_blank">here</a> if the online link is not working).</p>
<p><br> <br></p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="high-frequency-jet-ventilator-hfjv" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="high-frequency-jet-ventilator-hfjv"><span class="header-section-number">10.4</span> High-Frequency Jet Ventilator (HFJV)</h2>
<section id="indications" class="level3">
<h3 class="anchored" data-anchor-id="indications">Indications</h3>
<p>HFJV is indicated for neonates with specific conditions requiring gentle, high-frequency support:</p>
<ul>
<li>Pulmonary interstitial emphysema (PIE)</li>
<li>Respiratory distress syndrome complicated by pneumothorax</li>
<li>Meconium aspiration syndrome</li>
<li>Atelectatic pulmonary disease due to secretions or intrapulmonary inflammatory processes</li>
<li>Respiratory failure (RF) with hemodynamic compromise while on HFOV</li>
<li>Evolving bronchopulmonary dysplasia (BPD) in extremely immature infants</li>
</ul>
<p><strong>Note:</strong> At the initial roll-out stage, HFJV will <strong>not</strong> be used as a primary-intention mode of ventilation for extremely preterm infants unless a heterogeneous disease process is evident since birth.</p>
<p><br></p>
</section>
<section id="initial-settings" class="level3">
<h3 class="anchored" data-anchor-id="initial-settings">Initial Settings</h3>
<p>HFJV operates in tandem with a conventional mechanical ventilator (CMV), which provides PEEP, sigh breaths for recruitment, and bias flow for spontaneous breathing. Use the LifePort ETT adapter for delivery of tiny tidal volumes (&lt;1–2 mL/kg). Start with gentle pressures to avoid injury.</p>
<section id="jet-settings-hfjv---amplitudeventilation-for-co₂-control" class="level4">
<h4 class="anchored" data-anchor-id="jet-settings-hfjv---amplitudeventilation-for-co₂-control">Jet Settings (HFJV - Amplitude/Ventilation for CO₂ Control)</h4>
<ul>
<li><strong>PEEP</strong>: Typically 6–10 cmH₂O, or +1 cmH₂O above prior CMV settings; adjust to maintain MAP and oxygenation.</li>
<li><strong>PIP</strong>: Typically starting at 22–24 cmH₂O, may reach high 30’s to low 40’s in immature/sick lungs. PIP controls tidal volume and thus PaCO₂. Due to pressure attenuation in small airways, the lungs only see a small percentage of the set pressure.</li>
</ul>
<p><strong>Rate (bpm) and I:E Ratio:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rate (bpm)</th>
<th>I:E Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>420</td>
<td>1:6</td>
</tr>
<tr class="even">
<td>360</td>
<td>1:7</td>
</tr>
<tr class="odd">
<td>300</td>
<td>1:9</td>
</tr>
<tr class="even">
<td>240</td>
<td>1:12</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>RR</strong>: 240–660 bpm
<ul>
<li>420 bpm for non-extremely preterm or term infants</li>
<li>300–360 bpm for extremely preterm infants</li>
<li>240 bpm for PIE/air leak</li>
<li>Rate is chosen based on pathophysiology to optimize I:E ratio and minimize air trapping.</li>
<li><em>Note:</em> In HFJV, rate does <strong>not</strong> affect tidal volume, but may influence minute ventilation and MAP.</li>
</ul></li>
<li><strong>i-Time</strong>: 0.02 sec (affects tidal volume). Do not change unless maxed out on PIP and RR and CO₂ remains elevated. Increase by 0.002 sec if necessary to a maximum of 0.03 sec (caution: dramatically affects CO₂ and may cause lung injury).</li>
</ul>
</section>
<section id="sigh-breath-settings-for-lung-recruitment-contraindicated-in-active-air-leaks" class="level4">
<h4 class="anchored" data-anchor-id="sigh-breath-settings-for-lung-recruitment-contraindicated-in-active-air-leaks">Sigh Breath Settings (For Lung Recruitment; Contraindicated in Active Air Leaks)</h4>
<ul>
<li><strong>PIP</strong>: Use low ΔP &lt;5–10 cmH₂O above PEEP for gentle recruitment.</li>
<li><strong>RR</strong>: Typically 0–6 bpm; temporary use only (no more than 30 min if ≥4 bpm) to avoid overdistension. Set to 0 if air leaks are present.</li>
<li><strong>I-Time</strong>: Typically 0.4–0.6 sec; extend for recruitment if needed.</li>
</ul>
</section>
<section id="backup-simv-ps-support-mode-during-hfjv-alarmmalfunction" class="level4">
<h4 class="anchored" data-anchor-id="backup-simv-ps-support-mode-during-hfjv-alarmmalfunction">Backup SIMV + PS Support Mode (During HFJV Alarm/Malfunction)</h4>
<p>Switch to this CMV mode temporarily if HFJV fails:</p>
<ul>
<li><strong>PEEP</strong>: Match the same setting while on HFJV</li>
<li><strong>PIP</strong>: Typically matching or 2 cmH₂O below HFJV PIP</li>
<li><strong>RR</strong>: 20–40 bpm based on patient needs</li>
<li><strong>I-Time</strong>: 0.3–0.4 sec based on RR</li>
<li><strong>Pressure Support</strong>: 10–12 cmH₂O for 2.5 ETT</li>
</ul>
<p><br></p>
</section>
</section>
<section id="oxygenation-management" class="level3">
<h3 class="anchored" data-anchor-id="oxygenation-management">Oxygenation Management</h3>
<ul>
<li>Titrate FiO₂ (on both CMV and Jet ventilator) to maintain target SpO₂.</li>
<li>Consider increasing PEEP/MAP or performing recruitment maneuvers to improve lung volume.</li>
<li>Notify MD if FiO₂ &gt; 60% acutely.</li>
</ul>
<p><br></p>
</section>
<section id="additional-initiation-steps" class="level3">
<h3 class="anchored" data-anchor-id="additional-initiation-steps">Additional Initiation Steps</h3>
<ul>
<li>Ensure servo pressure stabilizes at 1.5–4.0 psi (auto-adjusts flow to maintain PIP).</li>
<li>Perform <strong>“Rule of 5’s” Recruitment Maneuver</strong> if indicated (e.g., for atelectasis): 5 breaths at PIP 5 cmH₂O above PEEP, i-Time 0.5 sec, every 5 minutes. Consider q-shift for ongoing recruitment (avoid in active air leaks).</li>
<li>Monitor changes in lung dynamics via servo pressure trends.</li>
</ul>
<p><br></p>
</section>
<section id="management-and-titration" class="level3">
<h3 class="anchored" data-anchor-id="management-and-titration">Management and Titration</h3>
<p>Adjust settings based on blood gases, chest X-ray, and clinical status.<br>
<strong>Primary goals:</strong> - Control CO₂ with Jet PIP/RR - Maintain oxygenation/lung volume with PEEP/MAP - Minimize sigh breaths in air leak-prone conditions</p>
<section id="general-titration-guidelines" class="level4">
<h4 class="anchored" data-anchor-id="general-titration-guidelines">General Titration Guidelines</h4>
<ul>
<li><strong>CO₂ Management</strong>: Increase Jet PIP by 1–2 cmH₂O if PaCO₂ is high; decrease if low. If PIP is maxed, consider lowering RR for air trapping.</li>
<li><strong>Oxygenation</strong>: Adjust PEEP by 1–2 cmH₂O. Use sigh breaths sparingly for recruitment.</li>
<li><strong>Weaning</strong>: Decrease PIP as CO₂ improves; reduce PEEP/FiO₂ as oxygenation stabilizes. Transition back to HFOV when heterogeneous lung pathology is resolved, or to CMV (invasive NAVA) when ready for extubation (to bubble CPAP or non-invasive NAVA).</li>
<li><strong>Monitoring</strong>: Trend servo pressure (rises with decreased compliance/obstruction; falls with leaks/improved compliance). Check ETT position and suction as needed. Obtain ABG 15–30 min after changes.</li>
</ul>
<p><br></p>
</section>
</section>
<section id="disease-specific-strategies" class="level3">
<h3 class="anchored" data-anchor-id="disease-specific-strategies">Disease-Specific Strategies</h3>
<p>Adapt based on primary diagnosis:</p>
<ul>
<li><strong>BPD or evolving BPD</strong>: Minimize air trapping/hyperinflation. Use low Jet PIP/RR (e.g., 240–300 bpm), low PEEP, minimal sigh breaths (low ΔP &lt;5 cmH₂O, short i-Time). Consider q-shift Rule of 5’s.</li>
<li><strong>PIE or Air Leaks</strong>: Promote healing. Initiate early; use low Jet RR (240 bpm) for extended expiratory time; optimize PEEP for MAP; avoid sigh breaths.</li>
<li><strong>MAS</strong>: Promote airway clearance via sweeping exhalation. Use low RR; may consider increasing i-Time for term infants; consider sigh breaths.</li>
</ul>
<p><br></p>
</section>
<section id="troubleshooting-1" class="level3">
<h3 class="anchored" data-anchor-id="troubleshooting-1">Troubleshooting</h3>
<p>Use servo pressure trends and alarms to identify issues.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 33%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Issue</th>
<th>Possible Causes</th>
<th>Actions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Low Servo Pressure (&lt;1.5 psi)</td>
<td>Decreased lung compliance, ETT obstruction/kink, secretions, worsening disease</td>
<td>Suction ETT, check tube position, reassess (X-ray/ABG), decrease PIP if overventilating</td>
</tr>
<tr class="even">
<td>High Servo Pressure (&gt;4.0 psi)</td>
<td>Improved compliance, air leak, tube malposition, disconnect</td>
<td>Check connections/ETT seal, increase PIP if underventilating, notify MD for potential ETT upsizing</td>
</tr>
<tr class="odd">
<td>High PaCO₂ (Hypercapnia)</td>
<td>Inadequate ventilation, air trapping</td>
<td>Increase Jet PIP by 1–2 cmH₂O; if maxed, decrease RR or increase i-Time (caution); ensure adequate expiratory time</td>
</tr>
<tr class="even">
<td>Low PaCO₂ (Hypocapnia)</td>
<td>Overventilation</td>
<td>Decrease Jet PIP; increase RR if needed</td>
</tr>
<tr class="odd">
<td>Hypoxemia (High FiO₂)</td>
<td>Atelectasis, low MAP</td>
<td>Increase PEEP by 1 cmH₂O; perform recruitment maneuver (if no air leaks); optimize position</td>
</tr>
<tr class="even">
<td>Alarms (High/Low Pressure)</td>
<td>Circuit disconnect, obstruction, patient agitation</td>
<td>Inspect circuit/patient box; reset ventilator; switch to backup SIMV+PS if persistent</td>
</tr>
<tr class="odd">
<td>No Improvement/Failure</td>
<td>Wrong rate for pathophysiology, active air leaks</td>
<td>Reassess diagnosis; consider switch to HFOV; notify MD</td>
</tr>
</tbody>
</table>
<p><strong>Note on HFJV vs HFOV</strong>: HFJV has passive exhalation, variable I:E ratio, and low flow. HFOV has active exhalation and fixed I:E ratio.</p>
<p><br></p>
</section>
<section id="dot-phrases" class="level3">
<h3 class="anchored" data-anchor-id="dot-phrases">Dot-phrases</h3>
<ul>
<li><code>.JETSETTINGS</code></li>
<li><code>.JETSETTINGSHINT</code></li>
</ul>
<p><br> <br></p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="sec-extubation" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="sec-extubation"><span class="header-section-number">10.5</span> Extubation Workflow for ELGAN/ELBW</h2>
<section id="background" class="level3">
<h3 class="anchored" data-anchor-id="background">Background</h3>
<ul>
<li>Assessing extubation readiness in ELGAN/ELBW babies is challenging.</li>
<li>Higher extubation failure rates are tolerated in small babies compared to those born at a higher gestational age (GA) or birth weight (BW).</li>
<li>Early successful extubation correlates with better outcomes, but failure may increase morbidity and mortality.</li>
<li>Creating a standardized workflow for extubation decision-making and procedures can reduce mental burden for the multidisciplinary care team.</li>
</ul>
<p><br></p>
</section>
<section id="timing-of-successful-extubation-in-elganelbw-from-different-studies" class="level3">
<h3 class="anchored" data-anchor-id="timing-of-successful-extubation-in-elganelbw-from-different-studies">Timing of successful extubation in ELGAN/ELBW from Different Studies</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th><strong><em>GA</em></strong></th>
<th><strong>APEX Study</strong></th>
<th><strong>Norway Study</strong></th>
<th><strong>Canada Study</strong></th>
<th><strong>Iowa City, USA</strong></th>
<th><strong>Kanagawa, Japan</strong></th>
<th><strong>Uppsala, Sweden</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>22-23 weeks</em></td>
<td>28 [27-29.3]</td>
<td>28 [27-29]</td>
<td>29.4 [27.4-31.1]</td>
<td>31 [29-33]</td>
<td>36.1 [35-37.2]</td>
<td>29</td>
</tr>
<tr class="even">
<td><em>24 weeks</em></td>
<td>27 [25-29]</td>
<td>27 [25-29]</td>
<td>29.1 [26.9-31.0]</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr class="odd">
<td><em>25 weeks</em></td>
<td>27 [25-29]</td>
<td>26 [26-28]</td>
<td>28.1 [25.9-30.3]</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr class="even">
<td><em>26 weeks</em></td>
<td>27 [26-29]</td>
<td>N/A</td>
<td>27.3 [26.3-29.7]</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
<tr class="odd">
<td><em>27 weeks</em></td>
<td>27 [27-28]</td>
<td>N/A</td>
<td>27.6 [27.3-29.1]</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
</tr>
</tbody>
</table>
<p><em>Seminars in Fetal and Neonatal Medicine, 2023-10-01, Vol 28, Issue 5, Article 101489</em></p>
<section id="consensus" class="level4">
<h4 class="anchored" data-anchor-id="consensus">Consensus</h4>
<ul>
<li>Adhere to the respiratory protocol for infants on invasive NAVA, testing for up to 24 hours before extubation.</li>
<li>Extubation decisions require agreement between incoming and outgoing neonatologists.</li>
<li>Perform extubation in the morning as possible with both neonatologists present in the hospital.</li>
<li>Ensure at least one neonatologist is present during extubation to evaluate the immediate need for reintubation.</li>
<li>Keep supplies ready at the bedside.</li>
<li>Maintain a low threshold for reintubation and restarting HFOV.</li>
<li>Consider administering a loading dose of caffeine (20 mg/kg) prior to extubation.</li>
</ul>
<p><br></p>
</section>
</section>
<section id="checklist" class="level3">
<h3 class="anchored" data-anchor-id="checklist">Checklist</h3>
<p><a href="files/extubation-checklist.pdf" target="_blank">Click to Download Extubation Checklist</a></p>
<p><img src="Figures/Extubation-pic1.jpg" class="img-fluid"></p>
<section id="interface-choice" class="level4">
<h4 class="anchored" data-anchor-id="interface-choice">Interface choice</h4>
<ul>
<li>Fisher &amp; Paykel Flexitrunk interface
<ul>
<li>Prong / mask</li>
<li>Bonnet / Tortle cap<br>
<em>even if extubating to Non-Invasive NAVA, Fisher &amp; Paykel interface should still be used, with the goal of weaning to bubble CPAP as soon as the infant is ready</em></li>
</ul></li>
</ul>
</section>
<section id="non-invasive-mode-selection" class="level4">
<h4 class="anchored" data-anchor-id="non-invasive-mode-selection">Non-invasive mode selection</h4>
<ul>
<li>Bubble CPAP, pressure level: ________</li>
<li>Non-invasive NAVA (e.g., high MAP, high NAVA level, etc.)
<ul>
<li>Edi catheter inserted and depth verified on Servo vent screen</li>
<li>NAVA and backup settings entered in the Servo machine</li>
<li>Starting pressure and FiO2</li>
</ul></li>
</ul>
</section>
<section id="resuscitation-equipment" class="level4">
<h4 class="anchored" data-anchor-id="resuscitation-equipment">Resuscitation equipment</h4>
<ul>
<li>T-piece set to 20/5 cmH<sub>2</sub>O</li>
<li>ET tube 2.5 and 3.0; stylet</li>
<li>Laryngoscope size 0 and 00</li>
<li>Suction catheter 8 and 10 Fr</li>
</ul>
</section>
<section id="medication" class="level4">
<h4 class="anchored" data-anchor-id="medication">Medication</h4>
<ul>
<li>Racemic epinephrine</li>
<li>Caffeine</li>
</ul>
</section>
</section>
<section id="procedures" class="level3">
<h3 class="anchored" data-anchor-id="procedures">Procedures</h3>
<ol type="1">
<li><p>Set up resuscitation equipment<br>
<img src="Figures/extubation-pic2.jpg" class="img-fluid" width="300"></p></li>
<li><p>Attach non-invasive interface to the infant.<br>
<img src="Figures/extubation-pic3.jpg" class="img-fluid" width="300"></p>
<p><em>If planning to extubate to bubble CPAP, disconnect one limb first (either incoming or outgoing) before attaching the Flexitrunk and nasal interface to the infant.</em><br>
<img src="Figures/extubation-pic4.jpg" class="img-fluid" width="300"></p>
<p><em>In order for the F/P prong to fit in the nose, ETT tapes may need to be removed first, depending on whether the nostrils are partially obstructed by the tape or not.</em><br>
<img src="Figures/extubation-pic5.jpg" class="img-fluid" width="300"></p></li>
<li><p>Suction the ET tube<br>
<img src="Figures/extubation-pic6.jpg" class="img-fluid" width="300"></p></li>
<li><p>Untape and remove the ET tube while connecting the previously disconnected limb to the bubble CPAP device, <strong>or</strong> switching the vent mode to NON-INVASIVE NAVA</p></li>
</ol>
</section>
<section id="what-to-expect-after-extubation" class="level3">
<h3 class="anchored" data-anchor-id="what-to-expect-after-extubation">What to expect after extubation</h3>
<p>Due to fluid shift, the lung fields are expected to <strong>white out</strong> following extubation for up to 24-48 hrs.</p>
<section id="pre-extubation-post-extubation-timeline" class="level4">
<h4 class="anchored" data-anchor-id="pre-extubation-post-extubation-timeline">Pre-extubation / Post-extubation Timeline</h4>
<ul>
<li><strong>Pre-extubation</strong><br>
<img src="Figures/post-extubation1.png" class="img-fluid" width="300"></li>
<li><strong>Post-extubation 12 hrs</strong><br>
<img src="Figures/post-extubation2.png" class="img-fluid" width="300"></li>
<li><strong>24 hrs</strong><br>
<img src="Figures/post-extubation3.png" class="img-fluid" width="300"></li>
<li><strong>36 hrs</strong><br>
<img src="Figures/post-extubation4.png" class="img-fluid" width="300"></li>
<li><strong>Four days later</strong><br>
<img src="Figures/post-extubation5.png" class="img-fluid" width="300"></li>
</ul>
<p>Adjust pressure and FiO<sub>2</sub> accordingly to compensate during fluid shift, allowing time to recover.</p>
<ul>
<li>Serial chest x-ray and blood gas assessment as needed.<br>
</li>
<li>Fluid management.<br>
</li>
<li>Low threshold to re-intubate if having significant work of breathing and/or respiratory acidosis (e.g., pCO<sub>2</sub> &gt; 75, pH &lt; 7.1, etc.)</li>
</ul>
<p><br> <br></p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="cardiopulmonary-events---spells" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="cardiopulmonary-events---spells"><span class="header-section-number">10.6</span> Cardiopulmonary Events - Spells</h2>
<p><br></p>
<section id="regional-definition" class="level3">
<h3 class="anchored" data-anchor-id="regional-definition">Regional Definition</h3>
<section id="sec-apnea" class="level4">
<h4 class="anchored" data-anchor-id="sec-apnea">Apnea</h4>
<ul>
<li>Pause in breathing for 20 seconds, or</li>
<li>Pause in breathing with heart rate &lt; 80bpm and/or SpO<sub>2</sub> &lt; 80% for ≥ 10 seconds.</li>
</ul>
</section>
<section id="sec-bradycardia" class="level4">
<h4 class="anchored" data-anchor-id="sec-bradycardia">Bradycardia</h4>
<ul>
<li>Does not meeting criteria for Apnea;</li>
<li>Any drift in HR &lt; 80bpm for ≥ 10 sec requiring intervention other than removing the bottle if during feeding.</li>
</ul>
</section>
<section id="sec-desaturation" class="level4">
<h4 class="anchored" data-anchor-id="sec-desaturation">Desaturation</h4>
<ul>
<li>Does not meeting criteria for Apnea or Bradycardia;</li>
<li>SpO2 &lt; 80% for ≥ 10 sec requiring intervention other than removing the bottle if during feeding.</li>
</ul>
<p><br></p>
</section>
</section>
<section id="types-of-bd-spells" class="level3">
<h3 class="anchored" data-anchor-id="types-of-bd-spells">Types of B/D spells</h3>
<section id="feeding-related-spells-feeding-spells" class="level4">
<h4 class="anchored" data-anchor-id="feeding-related-spells-feeding-spells">Feeding-related spells (feeding spells)</h4>
<ul>
<li><a href="#sec-apnea">Apnea</a> or <a href="#sec-bradycardia">bradycardia</a> occurred during oral feeding and/or up to 30 min after completion of feeding.</li>
</ul>
</section>
<section id="sleep-spells" class="level4">
<h4 class="anchored" data-anchor-id="sleep-spells">Sleep spells</h4>
<ul>
<li>Spells that are not considered feeding-related.</li>
</ul>
<p><br></p>
</section>
</section>
<section id="bedside-practice-update" class="level3">
<h3 class="anchored" data-anchor-id="bedside-practice-update">Bedside Practice Update</h3>
<section id="update-1" class="level4">
<h4 class="anchored" data-anchor-id="update-1">Update 1:</h4>
<p><em>Do not intervene in the first 10 sec of a spell, unless:</em></p>
<ul>
<li>Life-threatening (e.g.&nbsp;aspiration, airway compromise, etc.).<br>
</li>
<li>Heart rate progress to &lt; 60/min.</li>
</ul>
</section>
<section id="update-2" class="level4">
<h4 class="anchored" data-anchor-id="update-2">Update 2:</h4>
<p><em>Do not document events where lowest HR ≥ 80/min and lowest SpO<sub>2</sub> ≥ 80% in the flowsheet Apnea/Bradycardia tab:</em></p>
<ul>
<li>These are not A/B/D events by definition.<br>
</li>
<li>If persistent/recurrent SpO<sub>2</sub> 80-89% and intervention (e.g.&nbsp;stimulation, flow/O<sub>2</sub>) is needed, please notify MD and document in the notes.</li>
</ul>
<p><br></p>
</section>
</section>
<section id="sec-protocol-sleep-spells-monitoring" class="level3">
<h3 class="anchored" data-anchor-id="sec-protocol-sleep-spells-monitoring">Sleep spells monitoring</h3>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-r28n{font-size:18px;text-align:center;vertical-align:middle}
.tg .tg-mjre{color:#f56b00;font-size:18px;text-align:center;vertical-align:middle}
.tg .tg-13pz{font-size:18px;text-align:center;vertical-align:top}
.tg .tg-9apd{background-color:#c0c0c0;font-size:18px;text-align:center;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 480px">
<colgroup>
<col style="width: 80px">
<col style="width: 80px">
<col style="width: 160px">
<col style="width: 160px">
</colgroup>
<thead>
<tr>
<th class="tg-mjre" colspan="2" rowspan="2">
Requiring intervention
</th>
<th class="tg-13pz" colspan="2">
Heart rate
</th>
</tr>
<tr>
<th class="tg-13pz">
<span style="font-weight:400;font-style:normal;text-decoration:none">≥ 80/min</span>
</th>
<th class="tg-13pz">
&lt; 80/min
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-r28n" rowspan="2">
SpO<sub>2</sub>
</td>
<td class="tg-13pz">
<span style="font-weight:400;font-style:normal;text-decoration:none">≥</span> 80%
</td>
<td class="tg-9apd">
Not a spell
</td>
<td class="tg-r28n" rowspan="2">
3 days
</td>
</tr>
<tr>
<td class="tg-r28n">
&lt; 80%
</td>
<td class="tg-r28n">
1 day
</td>
</tr>
</tbody>
</table>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-r28n{font-size:18px;text-align:center;vertical-align:middle}
.tg .tg-mjre{color:#f56b00;font-size:18px;text-align:center;vertical-align:middle}
.tg .tg-15qn{background-color:#c0c0c0;font-size:18px;text-align:center;vertical-align:middle}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 640px">
<colgroup>
<col style="width: 80px">
<col style="width: 80px">
<col style="width: 240px">
<col style="width: 240px">
</colgroup>
<thead>
<tr>
<th class="tg-mjre" colspan="2" rowspan="2">
Self-resolved
</th>
<th class="tg-r28n" colspan="2">
Heart rate
</th>
</tr>
<tr>
<th class="tg-r28n">
<span style="font-weight:400;font-style:normal;text-decoration:none">≥ 80/min</span>
</th>
<th class="tg-r28n">
&lt; 80/min
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-r28n" rowspan="2">
SpO<sub>2</sub>
</td>
<td class="tg-r28n">
<span style="font-weight:400;font-style:normal;text-decoration:none">≥</span> 80%
</td>
<td class="tg-15qn">
Not a spell
</td>
<td class="tg-r28n">
No color change: insignificant <br>With color change: 1 day
</td>
</tr>
<tr>
<td class="tg-r28n">
&lt; 80%
</td>
<td class="tg-r28n">
No color change: insignificant <br>With color change: 1 day
</td>
<td class="tg-r28n">
1 day
</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>This algorithm is meant for preterm infants whose baseline SpO<sub>2</sub> is within normal range not requiring any respiratory support who are otherwise taking full or near-full PO and are close to NICU discharge.<br>
</li>
<li>This algorithm may not be applicable to term infants who respiratory control and suck-swallow-breath coordination are mature at birth. Spells in these infants are usually due to maternal influence, airway abnormalities, or ongoing pulmonary pathologies.<br>
</li>
<li>This algorithm should not be applied to A/B/D events that occur in the delivery room or around time of admission.<br>
</li>
<li>Isolated obstructive apnea is rare. Skin-to-skin-related spells are usually obstructive in nature. Clinical ruling of those events should be at the treating neonatologist’s discretion.<br>
</li>
<li><strong>Isolated SpO<sub>2</sub> in the 80-89% range on the day of hospital discharge, although not a spell by definition, is equal to a failed CCHD screening, and therefore should not be ignored if occurred within 1 day of discharge.</strong></li>
</ul>
</div>
</div>
<p><br></p>
</section>
<section id="sec-protocol-feeding-spells-monitoring" class="level3">
<h3 class="anchored" data-anchor-id="sec-protocol-feeding-spells-monitoring">Feeding spells monitoring</h3>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-na62{font-size:18px;font-weight:bold;text-align:left;vertical-align:middle}
.tg .tg-axmw{font-size:18px;font-weight:bold;text-align:center;vertical-align:middle}
.tg .tg-r28n{font-size:18px;text-align:center;vertical-align:middle}
.tg .tg-ewmv{font-size:18px;text-align:left;vertical-align:middle}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 562px">
<colgroup>
<col style="width: 361px">
<col style="width: 201px">
</colgroup>
<thead>
<tr>
<th class="tg-na62">
Intervention
</th>
<th class="tg-axmw">
Monitoring period
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-ewmv">
Remove bottle only, no color change
</td>
<td class="tg-r28n">
insignificant
</td>
</tr>
<tr>
<td class="tg-ewmv">
Remove bottle only, with color change
</td>
<td class="tg-r28n">
1 day
</td>
</tr>
<tr>
<td class="tg-ewmv">
Stimulation and/or flow/O<sub>2</sub>
</td>
<td class="tg-r28n">
1 day
</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Before discharge, designated primary home caregiver should be competent in identifying feeding-related distress and knowledge of timely intervention.</li>
</ul>
</div>
</div>
<p><br></p>
</section>
<section id="spell-watch-after-hepatitis-b-vaccine-administration" class="level3">
<h3 class="anchored" data-anchor-id="spell-watch-after-hepatitis-b-vaccine-administration">Spell watch after Hepatitis B vaccine administration</h3>
<section id="during-spell-watch" class="level4">
<h4 class="anchored" data-anchor-id="during-spell-watch">During spell watch</h4>
<p>If Hepatitis B vaccine is administered during spell watch, the spell watch period will be modified to include 48 hrs of monitoring following vaccine administration.</p>
<ul>
<li>Example: if baby is being monitored from 2/10 to 2/13 (72 hrs), and Hepatitis B vaccine if administered on 2/12, the monitoring period will be extended to 2/14.</li>
</ul>
</section>
<section id="not-during-spell-watch" class="level4">
<h4 class="anchored" data-anchor-id="not-during-spell-watch">Not during spell watch</h4>
<p>No need to monitor for spells after vaccine administration.</p>
</section>
</section>
<section id="sleep-study" class="level3">
<h3 class="anchored" data-anchor-id="sleep-study">Sleep study</h3>
<p>When an infant is likely to need a sleep study, please contact the following people by starting a Teams group chat:</p>
<ul>
<li>Eva Montoya</li>
<li>Julie Dewitte</li>
<li>Dennis Hwang</li>
<li>Huy Truong</li>
<li>Add any subspecialists for sleep study availability and consultation</li>
</ul>
<p><br> <br> </p><div style="page-break-after: always;"></div><p></p>
</section>
</section>
<section id="respiratory-support-weaning-algorithm" class="level2 column-screen-right" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="respiratory-support-weaning-algorithm"><span class="header-section-number">10.7</span> Respiratory Support Weaning Algorithm</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

a["&lt;strong&gt;Respiratory support at 32 weeks PMA&lt;/strong&gt;"] --&gt; b["&lt;span style='color:red;'&gt;SCENARIO 1:&lt;br&gt;CPAP 4cmH&lt;sub&gt;2&lt;/sub&gt;O FiO&lt;sub&gt;2&lt;/sub&gt; 21% for &gt; 24hrs&lt;/span&gt;"]
a --&gt; c["&lt;span style='color:red;'&gt;SCENARIO 2:&lt;br&gt;CPAP 5cmH&lt;sub&gt;2&lt;/sub&gt;O FiO&lt;sub&gt;2&lt;/sub&gt; 21%&lt;/span&gt;"]
a --&gt; d["&lt;span style='color:red;'&gt;SCENARIO 3:&lt;br&gt;CPAP 5cmH&lt;sub&gt;2&lt;/sub&gt;O FiO&lt;sub&gt;2&lt;/sub&gt; &amp;gt;21%&lt;/span&gt;"]
a --&gt; e["&lt;span style='color:red;'&gt;SCENARIO 4:&lt;br&gt;CPAP &gt;5cmH&lt;sub&gt;2&lt;/sub&gt;O&lt;/span&gt;"]
c --&gt; b
b --&gt; f("Room air trial")
f --&gt; g["Successful"]
f --&gt; h["Failed"]
g --&gt; j["Room air"]
h --&gt; i("Wean to HFNC 2LPM for 24-72hrs")
i --&gt; p["FiO2&lt;sub&gt;2&lt;/sub&gt; remained at 21%"]
i --&gt; q["FiO&lt;sub&gt;2&lt;/sub&gt; increased to &gt;21%"]
q --&gt; s["Wean to 21%"]
s --&gt; p
p --&gt; r["Wean flow by 0.25-0.5PM q24-48hrs"]
d --&gt; k("Wean FiO&lt;sub&gt;2&lt;/sub&gt; to 21% by 33 weeks PMA")
k --&gt; l["Successful"]
k --&gt; m["Unsuccessful"]
l --&gt; b
m --&gt; o("Consider Diuretics algorithm")
e --&gt; o
q --&gt; o
r --&gt; j
r --&gt; t["Frequent desats during weaning/&lt;br&gt;FiO&lt;sub&gt;2&lt;/sub&gt; increased to &gt; 21%"]
t --&gt; u("Consider microflow")
u --&gt; j
o --&gt; v["Able to wean to CPAP 5cmH&lt;sub&gt;2&lt;/sub&gt;O FiO&lt;sub&gt;2&lt;/sub&gt; 21%&lt;br&gt;by 33 weeks PMA?"]
v --&gt; w["Yes"]
v --&gt; x["No"]
x --&gt; y("Echo for late PH assessment")
w --&gt; c
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="diuretics-algorithm" class="level2 column-screen-right" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="diuretics-algorithm"><span class="header-section-number">10.8</span> Diuretics Algorithm</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

a["Obtain baseline Chest X-Ray"] --&gt; b("Pulmonary congestion/edema?")
b --&gt; c("Yes")
b --&gt; d("No")
d --&gt; e["Empiric trial of diuretics"]
d --&gt; f["No role of diuretics"]
c --&gt; g["Lasix IV 1mg/kg/day or,&lt;br/&gt; PO 2mg/kg/day for 2 days&lt;br/&gt;(dosing up for discussion)"]
e --&gt; g
g --&gt; h("Improved?")
h --&gt; i("Yes, FiO&lt;sub&gt;2&lt;/sub&gt; 21%")
h --&gt; j("Yes, but FiO&lt;sub&gt;2&lt;/sub&gt; still &gt;21%")
j --&gt; m["Consider Aldactazide for long-term therapy"]

h --&gt; k("No")
k --&gt; m
k --&gt; l["Consider further workup and/or&lt;br&gt;wean pressure/flow empirically"]
f --&gt; l
l --&gt; p["Consider repeating Chest X-Ray"]
l --&gt; n["Echo for late PH assessment&lt;br/&gt;Especially if frequent desats clinically"]
l --&gt; r["Consider CBC for Anemia"]
i --&gt; o["&lt;strong&gt;Continue to wean&lt;br/&gt;respiratory support&lt;/strong&gt;"]
m --&gt; o
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<p><br><br></p><div style="page-break-after: always;"></div><p></p>
<section id="bronchouplmonary-dysplasia-bpd" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="bronchouplmonary-dysplasia-bpd"><span class="header-section-number">10.9</span> Bronchouplmonary dysplasia (BPD)</h2>
<p><br></p>
<section id="sec-bpd-bundle" class="level3">
<h3 class="anchored" data-anchor-id="sec-bpd-bundle">No-BPD prevention bundle (BPD Bundle)</h3>
<section id="general-criteria" class="level4">
<h4 class="anchored" data-anchor-id="general-criteria">General criteria</h4>
<ul>
<li>GA &lt; 32 weeks OR BW &lt; 1,500g</li>
</ul>
</section>
<section id="injection-meds" class="level4">
<h4 class="anchored" data-anchor-id="injection-meds">Injection meds</h4>
<ul>
<li><strong>Vitamin A</strong>
<ul>
<li>Reserved for BW &lt; 1,000g AND GA &lt; 28 weeks requiring respiratory support after birth</li>
<li>Dose: 5,000 units 3 times per week for 12 doses (4 weeks)<br>
</li>
</ul></li>
<li><strong>Epogen</strong>
<ul>
<li>Dose: 250 units/kg/dose SQ Mon Wed Fr starting at DOL7</li>
</ul></li>
</ul>
</section>
<section id="enteral-meds" class="level4">
<h4 class="anchored" data-anchor-id="enteral-meds">Enteral meds</h4>
<p>When at 100ml/kg/day of enteral feeds:</p>
<ul>
<li><strong>Ferrous sulfate</strong> 3 mg/kg/dose PO twice daily</li>
<li><strong>Vitamin E</strong> 25 units oral twice daily</li>
</ul>
</section>
<section id="duration" class="level4">
<h4 class="anchored" data-anchor-id="duration">Duration</h4>
<ul>
<li>Discontinue Epogen, Ferrous sulfate, and Vitamin E when infants reach 36 weeks PMA</li>
</ul>
<p><br></p>
</section>
</section>
<section id="dart-protocol" class="level3">
<h3 class="anchored" data-anchor-id="dart-protocol">DART protocol</h3>
<p>10-day tapering course of dexamethasone sodium phosphate</p>
<ul>
<li>0.15 mg/kg/day for 3 days</li>
<li>0.10 mg/kg/day for 3 days</li>
<li>0.05 mg/kg/day for 2 days</li>
<li>0.02 mg/kg/day for 2 days</li>
</ul>
<p><em>Total of 0.89 mg/kg over 10 days</em></p>
<p><br> <br> </p><div style="page-break-after: always;"></div><p></p>
</section>
</section>
<section id="pneumothorax" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="pneumothorax"><span class="header-section-number">10.10</span> Pneumothorax</h2>
<section id="needle-thoractocentesis" class="level3">
<h3 class="anchored" data-anchor-id="needle-thoractocentesis">Needle thoractocentesis</h3>
</section>
<section id="chest-tube-placement" class="level3">
<h3 class="anchored" data-anchor-id="chest-tube-placement">Chest tube placement</h3>
<section id="turkel" class="level4">
<h4 class="anchored" data-anchor-id="turkel">Turkel<span>™</span></h4>
<ul>
<li>Size: 12-14 Fr</li>
<li>Suction: -15 cmH<sub>2</sub>O with the Pleur-evac<span>®</span> Chest Drainage System</li>
</ul>
<iframe width="560" height="315" src="https://www.youtube.com/embed/OlRUg7H1AGg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="">
</iframe>
</section>
<section id="pigtail-catheter" class="level4">
<h4 class="anchored" data-anchor-id="pigtail-catheter">Pigtail catheter</h4>
<p>Video credit: Neoreviews</p>
<iframe width="560" height="315" src="//players.brightcove.net/6056665225001/UxkvalZ0_default/index.html?videoId=6138641995001" allowfullscreen="" frameborder="0">
</iframe>
<hr>
<p><br></p>
<p>Modified SELDINGER TECHNIQUE (credit: <a href="https://shop.lww.com/MacDonald-s-Atlas-of-Procedures-in-Neonatology/p/9781496394255">MacDonald’s Atlas of Procedures in Neonatology</a>)</p>
<ul>
<li>GA:
<ul>
<li>&lt;28 wks: 6Fr</li>
<li>&gt;28 wks: 8Fr</li>
</ul></li>
<li>Equipment:
<ul>
<li>Introducer and J shaped guidewire</li>
<li>Finder Needle 20-gauge with syringe</li>
<li>Dilator</li>
<li>Adapter for external end of the catheter to connect to suction apparatus.</li>
</ul></li>
<li>Procedures (6 steps):
<ol type="1">
<li>Insert finder needle (introducer) on syringe 4<sup>th</sup> ICS</li>
<li>Remove the syringe while leaving the finder needle (introducer) &amp; feed the guidewire through introducer (finder needle) to 10cm mark.</li>
<li>Remove the introducer and finder needle while holding the guidewire steady and insert dilator over the guidewire 1-2cm skin and subcutaneous tissue (not chest wall).</li>
<li>Remove the dilator and insert the chest tube catheter over the guidewire until all holes are the chest (measures at ~ 7cm).</li>
<li>Maintain stability of the catheter and remove the guidewire.</li>
<li>Attach the catheter to the suction drainage device via luer adapter.</li>
</ol></li>
<li>Details and tips:
<ul>
<li><p>Mount the finder needle syringe with inserting the tip of the needle into the skin at the <span style="color:red;">4<sup>th</sup> intercostal space = nipple</span> between the <span style="color:red;">anterior and mid-axillary line <u>above the upper border of the 5<sup>th</sup> rib</u></span>.</p></li>
<li><p>Advance the finder needle slowly, simultaneously applying negative pressure to the syringe. The needle should be advanced perpendicular to the chest wall generally in the direction of the opposite shoulder.<br>
</p></li>
<li><p>Advance the needle until you feel the lack of resistance or “GIVE” and air entry is the syringe.<br>
<span style="color:red;">Do not evacuate more than 1-2mL of air. </span></p></li>
<li><p>While stabilizing the needle with 1 hand remove the syringe and insert guidewire through the finder needle.<br>
</p></li>
<li><p>Advance the guidewire until the depth marking at 10cm reaches the hub of the needle <span style="color:red;">Advanced the guidewire until 10cm mark that the needle hub</span></p></li>
<li><p>Maintain stability of the wire, remove the finder needle.<br>
</p></li>
<li><p>Feed the dilator over the wire and insert in a slow twisting motion to dilate the tract. Advanced the dilator only far enough to dilate the skin tract and parietal pleura. <span style="color:red;">This is normally about 1cm in preterm or 2cm in term infants.</span></p></li>
<li><p>Maintaining stability of the wire remove the dilator.</p></li>
<li><p>Insert the pigtail catheter over the wire and advanced it into the chest wall toward the apex of the lung (anteriorly and medially toward the 2<sup>nd</sup> intercostal space and midclavicular line) until <span style="color:red;">all the side holes of the catheter are inside the chest wall.</span></p></li>
<li><p>This requires uncoiling and holding the pigtail straight with 1 hand while advancing it onto the wire.</p></li>
<li><p>Maintaining stability of the catheter remove the guidewire. Catheter will spontaneously coil into a pigtail loop inside the pleural space.</p></li>
<li><p>Attach the luer adapter at the external end of the catheter and connect it the suction apparatus tubing.<br>
</p></li>
<li><p>Secure the chest tube with semipermeable transparent dressing and surgical tape.<br>
</p></li>
<li><p>Suture and the catheter in place is optional but typically not necessary as there is no skin incisions closed and the skin and trach will be snug against the counter.<br>
<span style="color:red;">Warning: it is easy to inadvertently compressed catheter with suture if secured too tightly.</span></p></li>
</ul></li>
</ul>
</section>
</section>
</section>
<section id="airway-edema" class="level2" data-number="10.11">
<h2 data-number="10.11" class="anchored" data-anchor-id="airway-edema"><span class="header-section-number">10.11</span> Airway Edema</h2>
<p><br></p>
<section id="treatment" class="level3">
<h3 class="anchored" data-anchor-id="treatment">Treatment</h3>
<p>Method 1:</p>
<ul>
<li>IV dexamethasone 0.25mg/kg/dose given ~4 hrs prior to scheduled extubastion then q8hrs for a total of 3 doses (Couser 1992).</li>
</ul>
<p>Method 2:</p>
<ul>
<li>IV dexamethasone 0.5mg/kg/dose q8 hrs for 3 doses with last dose administered 1 hr prior to scheduled extubation (Davis 2001).</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./death-workflows.html" class="pagination-link" aria-label="Fetal and Neonatal Death Workflows and Documentation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Fetal and Neonatal Death Workflows and Documentation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./cardiovascular.html" class="pagination-link" aria-label="Cardiovascular">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Cardiovascular</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>